[tool.poetry]
name = "dophon-logger"
version = "0.1.2r7"
description = "dophon logger module"
authors = ["CallMeE <ealohu@163.com>"]

[tool.poetry.dependencies]
python = "^3.6"
hues = "^0.2.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
dophon-properties = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
