# Represents a dummy claim


CLAIM = {
    'company_name': '',
    'deductible': '',
    'date_of_loss': '',
    'coverage_type': '',
    'owner_insured_or_claimant': '',
    'vehicle_plate_number': '',
    'vehicle_plate_state': '',
    'vehicle_vin': '',
    'vehicle_year': '',
    'vehicle_make': '',
    'vehicle_model': '',
    'vehicle_color': '',
    'id': '',
    'date_time_created': '',
    'owner_address_line1': '',
    'owner_address_line2': '',
    'owner_address_city': '',
    'owner_address_state': '',
    'owner_address_zip': '',
    'owner_last_name': '',
    'owner_first_name': '',
    'owner_company': '',
    'owner_address_line1': '',
    'owner_address_line2': '',
    'owner_address_city': '',
    'owner_address_state': '',
    'owner_address_zip': '',
    'owner_phone_mobile': '',
    'owner_phone_home': '',
    'owner_phone_work': '',
    'owner_phone_home': '',
    'owner_last_name': '',
    'owner_first_name': '',
    'owner_address_line1': '',
    'owner_address_line2': '',
    'owner_address_city': '',
    'owner_address_state': '',
    'owner_address_zip': '',
    'owner_phone_mobile': '',
    'owner_phone_home': '',
    'owner_phone_work': '',
    'owner_phone_home': '',
    'vehicle_location_name': '',
    'vehicle_location_phone': '',
    'vehicle_address_line1': '',
    'vehicle_address_line2': '',
    'vehicle_address_city': '',
    'vehicle_address_state': '',
    'vehicle_address_zip': ''
}
