
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-22T10:07:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "40fbf6de83466f3998297572d812af8712b8e657",
 "version": "0.5.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
