smtp:
    host: '208.81.212.70'
    port: 587
    use_tls: True
    username: 'customsmtp.globalrelay.com@mailarchivespool1.globalrelay.com'
    password: 'uaLKMLmhJXgLLEy2ZlKN'
    send_to_user: 'customsmtp.globalrelay.com+Preveil@mailarchivespool1.globalrelay.com'

cs:
    host: 'collections.preveil.com'
    port: 80
    use_tls: True