# Base Configuration file for artellapipe-tools-changelog in Plot Twist

# Defines icon of the tool
icon: changelog

# URL to tool documentation web page
url: https://plot-twist-short-film.github.io/plottwist-docs/pipeline/pipeline/tools/changelog/