# Base Configuration file for artellapipe-tools-artellamanager in Plot Twist

# Defines icon of the tool
icon: artellamanager

# URL to tool documentation web page
url: https://plot-twist-short-film.github.io/plottwist-docs/pipeline/pipeline/tools/artellamanager/