# Base Configuration file for artellapipe-tools-artellauploader in Plot Twist

# Defines icon of the tool
icon: artellauploader

# URL to tool documentation web page
url: https://plot-twist-short-film.github.io/plottwist-docs/pipeline/pipeline/tools/artellauploader/