# ref: https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip setuptools
  - pip install -U -r requirements_test.txt
  - wget -O - https://sh.rustup.rs | sh -s -- -y -q
install:
  - source $HOME/.cargo/env
  - pip install .
script: pytest --import-mode=append -v
