# see https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
edition = '2018'
name = "feature-mapper"
version = "0.1.10"
authors = ["Markus Strauss <mstrauss@users.noreply.github.com>"]
description = 'Transforms a binary feature matrix by applying a binary mapping matrix.'
license = 'GPL-3.0+'
homepage = 'https://github.com/complexity-science-hub/feature-mapper'

[dependencies]
rayon = "1.0"
log = "0.4"
env_logger = "0.7.1"

[lib]
name = "feature_mapper"
crate-type = ["cdylib"]

[package.metadata.maturin]
requires-dist = ["scipy~=1.3.0", "cffi~=1.13.0", "numpy~=1.17.0", "numpy-indexed~=0.3.5"]
