[tool.poetry]
name = "use-dir"
version = "0.1.3"
description = ""
authors = ["Mark Rawls <markrawls96@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
