#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['pygame == 1.9.6']

entry_points = \
{'console_scripts': ['snektris = snektris:main']}

setup(name='snektris',
      version='0.0.2',
      description='SNEKTRIS',
      author='Gabriel Kabbe',
      author_email='gabriel.kabbe@mail.de',
      url='https://github.com/gab50000/snektris',
      py_modules=['snektris'],
      install_requires=install_requires,
      entry_points=entry_points,
     )
