# coding: utf-8

"""
    SSPO Service

    The Scrum Software Process Ontology (SSPO) aims at establishing a common conceptualization on the Scrum domain, including roles, teams and projects.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sspo_client
from sspo_client.models.product_backlog_definition_ import ProductBacklogDefinition_  # noqa: E501
from sspo_client.rest import ApiException


class TestProductBacklogDefinition_(unittest.TestCase):
    """ProductBacklogDefinition_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductBacklogDefinition_(self):
        """Test ProductBacklogDefinition_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sspo_client.models.product_backlog_definition_.ProductBacklogDefinition_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
