[tool.poetry]
name = "et-micc-tools"
version = "0.0.5"
description = "<Enter a one-sentence description of this project here.>"
authors = ["Engelbert Tijskens <engelbert.tijskens@uantwerpen.be>"]
license = "MIT"

readme = 'README.rst'

repository = "https://github.com/etijskens/et-micc-tools"
homepage = "https://github.com/etijskens/et-micc-tools"

keywords = ['packaging', 'poetry']

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
tomlkit =  "^0.5.5"
cmake = "^3.15.3"
pybind11 = "^2.4.3"
numpy = "^1.17.4"

[tool.poetry.dev-dependencies]
pytest = "^4.4.2"

[tool.poetry.scripts]
build = "et_micc_tools:cli_build"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
