#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['hidiocore', 'hidiocore.client', 'hidiocore.schema']

package_data = \
{'': ['*']}

install_requires = \
['cython>=0.29', 'pycapnp-async>=0.7', 'pygtail>=0.11.1']

setup(name='hidiocore',
      version='0.1.0b3',
      description='HID-IO Python Library',
      author='Jacob Alexander',
      author_email='haata@kiibohd.com',
      url='http://hid-io.com',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
