__title__ = 'google-ime-skk-py'
__description__ = 'Google IME SKK server written in Python'
__url__ = 'https://github.com/chaploud/google-ime-skk-py'
__version__ = '0.0.1'
__author__ = 'chaploud'
__license__ = 'MIT'
