from json2struct import generate_struct_name, assure_uniform_object_structure
from json2struct import generate_struct_info, retype_nested_types, create_struct_strings
from json2struct import write_struct_file