---
- name: Destroy all running vms and associated disks
  hosts: all
  # NOTE(msimonin): quick fix for buster
  # The libvirt runtime dir (e.g with the socket) will be created in the home
  # dir instead of in /run/user/$UID
  # environment:
  #   XDG_RUNTIME_DIR: "/tmp/{{ g5k_user }}-runtime-dir"
  vars:
    libvirt_dir: /var/lib/libvirt/images/enos_vmong5k
  tasks:

  - name: list only running VMs
    shell: virsh list --uuid
    register: running_vms

  - debug: var=running_vms

  - name: Destroy running virtual machines (vm -1 / 1)
    shell: "virsh destroy {{ item }}"
    ignore_errors: yes
    loop: "{{ running_vms.stdout_lines }}"

  - name: Unmount a mounted volume
    mount:
      path: "{{ working_dir }}"
      state: unmounted

  - name: Unmount a mounted volume
    mount:
      path: "{{ libvirt_dir }}"
      state: unmounted

  - name: Remove the working directory
    file:
      path: "{{ working_dir }}"
      state: absent
      mode: 0711
