# coding: utf-8

"""
    SSPO Service

    The Scrum Software Process Ontology (SSPO) aims at establishing a common conceptualization on the Scrum domain, including roles, teams and projects.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScrumMasterTeamMembership_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'uuid': 'str',
        'scrum_master': 'str',
        'scrum_master_role': 'int',
        'development_team': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'uuid': 'uuid',
        'scrum_master': 'scrum_master',
        'scrum_master_role': 'scrum_master_role',
        'development_team': 'development_team'
    }

    def __init__(self, id=None, name=None, description=None, uuid=None, scrum_master=None, scrum_master_role=None, development_team=None):  # noqa: E501
        """ScrumMasterTeamMembership_ - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._description = None
        self._uuid = None
        self._scrum_master = None
        self._scrum_master_role = None
        self._development_team = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if description is not None:
            self.description = description
        if uuid is not None:
            self.uuid = uuid
        self.scrum_master = scrum_master
        if scrum_master_role is not None:
            self.scrum_master_role = scrum_master_role
        self.development_team = development_team

    @property
    def id(self):
        """Gets the id of this ScrumMasterTeamMembership_.  # noqa: E501


        :return: The id of this ScrumMasterTeamMembership_.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ScrumMasterTeamMembership_.


        :param id: The id of this ScrumMasterTeamMembership_.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ScrumMasterTeamMembership_.  # noqa: E501


        :return: The name of this ScrumMasterTeamMembership_.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ScrumMasterTeamMembership_.


        :param name: The name of this ScrumMasterTeamMembership_.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 200:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `200`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ScrumMasterTeamMembership_.  # noqa: E501


        :return: The description of this ScrumMasterTeamMembership_.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ScrumMasterTeamMembership_.


        :param description: The description of this ScrumMasterTeamMembership_.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def uuid(self):
        """Gets the uuid of this ScrumMasterTeamMembership_.  # noqa: E501


        :return: The uuid of this ScrumMasterTeamMembership_.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ScrumMasterTeamMembership_.


        :param uuid: The uuid of this ScrumMasterTeamMembership_.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def scrum_master(self):
        """Gets the scrum_master of this ScrumMasterTeamMembership_.  # noqa: E501


        :return: The scrum_master of this ScrumMasterTeamMembership_.  # noqa: E501
        :rtype: str
        """
        return self._scrum_master

    @scrum_master.setter
    def scrum_master(self, scrum_master):
        """Sets the scrum_master of this ScrumMasterTeamMembership_.


        :param scrum_master: The scrum_master of this ScrumMasterTeamMembership_.  # noqa: E501
        :type: str
        """
        if scrum_master is None:
            raise ValueError("Invalid value for `scrum_master`, must not be `None`")  # noqa: E501

        self._scrum_master = scrum_master

    @property
    def scrum_master_role(self):
        """Gets the scrum_master_role of this ScrumMasterTeamMembership_.  # noqa: E501


        :return: The scrum_master_role of this ScrumMasterTeamMembership_.  # noqa: E501
        :rtype: int
        """
        return self._scrum_master_role

    @scrum_master_role.setter
    def scrum_master_role(self, scrum_master_role):
        """Sets the scrum_master_role of this ScrumMasterTeamMembership_.


        :param scrum_master_role: The scrum_master_role of this ScrumMasterTeamMembership_.  # noqa: E501
        :type: int
        """

        self._scrum_master_role = scrum_master_role

    @property
    def development_team(self):
        """Gets the development_team of this ScrumMasterTeamMembership_.  # noqa: E501


        :return: The development_team of this ScrumMasterTeamMembership_.  # noqa: E501
        :rtype: int
        """
        return self._development_team

    @development_team.setter
    def development_team(self, development_team):
        """Sets the development_team of this ScrumMasterTeamMembership_.


        :param development_team: The development_team of this ScrumMasterTeamMembership_.  # noqa: E501
        :type: int
        """
        if development_team is None:
            raise ValueError("Invalid value for `development_team`, must not be `None`")  # noqa: E501

        self._development_team = development_team

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScrumMasterTeamMembership_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScrumMasterTeamMembership_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
