# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u987b\u77e5\u6807\u9898')),
                ('context', models.TextField(blank=True, null=True, verbose_name='\u987b\u77e5\u5185\u5bb9')),
                ('is_require', models.BooleanField(verbose_name='\u662f\u5426\u5fc5\u9009')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'bee_django_exam_notice',
            },
        ),
        migrations.AlterField(
            model_name='userexam',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bee_django_exam_grade', to='bee_django_exam.Grade', verbose_name='\u8003\u8bd5\u7ea7\u522b'),
        ),
        migrations.AddField(
            model_name='grade',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bee_django_exam.Notice', verbose_name='\u8003\u8bd5\u987b\u77e5'),
        ),
    ]
