# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 07:20
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_exam', '0012_remove_grade_cert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cert_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'media/exam/cert'), upload_to=b'', verbose_name='\u8bc1\u4e66\u56fe\u7247'),
        ),
    ]
