# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_exam', '0028_auto_20181219_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecertfield',
            name='text_height',
            field=models.IntegerField(blank=True, help_text='\u5355\u884c\u6587\u5b57\u65f6\u53ef\u4e0d\u586b\u5199\uff0c\u591a\u884c\u6587\u5b57\u65f6\u5fc5\u586b', null=True, verbose_name='\u6587\u5b57\u533a\u57df\u9ad8\u5ea6'),
        ),
    ]
