# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_exam', '0029_gradecertfield_text_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecertfield',
            name='text_align',
            field=models.CharField(help_text='\u6587\u5b57\u5728\u586b\u5199\u533a\u57df\u4e2d\u7684\u5bf9\u9f50\u65b9\u5f0f', max_length=180, verbose_name='\u6587\u5b57\u5bf9\u9f50'),
        ),
        migrations.AlterField(
            model_name='gradecertfield',
            name='text_bg_color',
            field=models.CharField(blank=True, help_text='\u9009\u586b', max_length=7, null=True, verbose_name='\u6587\u5b57\u533a\u57df\u80cc\u666f\u989c\u8272'),
        ),
        migrations.AlterField(
            model_name='gradecertfield',
            name='text_width',
            field=models.IntegerField(help_text='\u6587\u5b57\u8d85\u51fa\u6b64\u5bbd\u5ea6\u65f6\uff0c\u4f1a\u4e0d\u663e\u793a\u591a\u51fa\u7684\u6587\u5b57', verbose_name='\u6587\u5b57\u533a\u57df\u5bbd\u5ea6'),
        ),
    ]
