# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-22 05:33
from __future__ import unicode_literals

import bee_django_richtext.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_exam', '0031_auto_20191028_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='context',
            field=bee_django_richtext.custom_fields.RichTextField(app_name='bee_django_exam', blank=True, emotion=False, image_max_size=2, img=False, model_name='Notice', null=True, text_min_length=5, undo_redo=False, verbose_name='\u987b\u77e5\u5185\u5bb9'),
        ),
    ]
