
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4ea111ec0247cba582a850694449ea2962e063db",
 "version": "2216"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
