
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-19T15:56:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e5701f7c34ee38a0302dcaa09acbadcddad6b4a",
 "version": "0.0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
