[tool.poetry]
name = "healthbip"
version = "0.1.0"
description = "Django Application Healthchecks"
authors = ["Anders Innovations Oy <admin@anders.fi>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
Django = ">2"

[tool.poetry.dev-dependencies]
black = "=19.10b0"
flake8 = "^3.7"
isort = "^4.3"
mypy = "^0.740.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
