# coding: utf-8

"""
    Spotii Billing API

    API for Billing  # noqa: E501

    OpenAPI spec version: v1.0
    Contact: hello@nuclearo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from spotii_billing_client.api_client import ApiClient


class PluginConfigurationsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def plugin_configurations_create(self, body, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_create(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginConfiguration body: (required)
        :return: PluginConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_configurations_create_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.plugin_configurations_create_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def plugin_configurations_create_with_http_info(self, body, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_create_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginConfiguration body: (required)
        :return: PluginConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_configurations_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `plugin_configurations_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic', 'Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/plugin_configurations/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PluginConfiguration',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def plugin_configurations_delete(self, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_delete(key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str key: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_configurations_delete_with_http_info(key, **kwargs)  # noqa: E501
        else:
            (data) = self.plugin_configurations_delete_with_http_info(key, **kwargs)  # noqa: E501
            return data

    def plugin_configurations_delete_with_http_info(self, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_delete_with_http_info(key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str key: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_configurations_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'key' is set
        if ('key' not in params or
                params['key'] is None):
            raise ValueError("Missing the required parameter `key` when calling `plugin_configurations_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'key' in params:
            path_params['key'] = params['key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['Basic', 'Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/plugin_configurations/{key}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def plugin_configurations_list(self, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[PluginConfiguration]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_configurations_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.plugin_configurations_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def plugin_configurations_list_with_http_info(self, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[PluginConfiguration]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_configurations_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic', 'Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/plugin_configurations/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[PluginConfiguration]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def plugin_configurations_partial_update(self, body, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_partial_update(body, key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginConfigurationUpdate body: (required)
        :param str key: (required)
        :return: PluginConfigurationUpdate
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_configurations_partial_update_with_http_info(body, key, **kwargs)  # noqa: E501
        else:
            (data) = self.plugin_configurations_partial_update_with_http_info(body, key, **kwargs)  # noqa: E501
            return data

    def plugin_configurations_partial_update_with_http_info(self, body, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_partial_update_with_http_info(body, key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginConfigurationUpdate body: (required)
        :param str key: (required)
        :return: PluginConfigurationUpdate
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_configurations_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `plugin_configurations_partial_update`")  # noqa: E501
        # verify the required parameter 'key' is set
        if ('key' not in params or
                params['key'] is None):
            raise ValueError("Missing the required parameter `key` when calling `plugin_configurations_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'key' in params:
            path_params['key'] = params['key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic', 'Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/plugin_configurations/{key}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PluginConfigurationUpdate',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def plugin_configurations_read(self, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_read(key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str key: (required)
        :return: PluginConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_configurations_read_with_http_info(key, **kwargs)  # noqa: E501
        else:
            (data) = self.plugin_configurations_read_with_http_info(key, **kwargs)  # noqa: E501
            return data

    def plugin_configurations_read_with_http_info(self, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_read_with_http_info(key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str key: (required)
        :return: PluginConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_configurations_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'key' is set
        if ('key' not in params or
                params['key'] is None):
            raise ValueError("Missing the required parameter `key` when calling `plugin_configurations_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'key' in params:
            path_params['key'] = params['key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic', 'Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/plugin_configurations/{key}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PluginConfiguration',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def plugin_configurations_update(self, body, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_update(body, key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginConfigurationUpdate body: (required)
        :param str key: (required)
        :return: PluginConfigurationUpdate
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_configurations_update_with_http_info(body, key, **kwargs)  # noqa: E501
        else:
            (data) = self.plugin_configurations_update_with_http_info(body, key, **kwargs)  # noqa: E501
            return data

    def plugin_configurations_update_with_http_info(self, body, key, **kwargs):  # noqa: E501
        """Plugin configuration  # noqa: E501

        Plugins configuration per tenant level. For instance per-tenant plugin configuration for payment gateway CyberSource (access_keys, test/live environment).  System will generate a TENANT_CONFIGURATION_UPDATED/TENANT_CONFIGURATION_DELETED event, and such event can be handled in the plugin to refresh it's configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_configurations_update_with_http_info(body, key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginConfigurationUpdate body: (required)
        :param str key: (required)
        :return: PluginConfigurationUpdate
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_configurations_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `plugin_configurations_update`")  # noqa: E501
        # verify the required parameter 'key' is set
        if ('key' not in params or
                params['key'] is None):
            raise ValueError("Missing the required parameter `key` when calling `plugin_configurations_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'key' in params:
            path_params['key'] = params['key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic', 'Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/plugin_configurations/{key}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PluginConfigurationUpdate',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
