[tool.poetry]
name = "hilale"
version = "0.1.0"
description = ""
authors = ["rkshrksh <aarkaygautam@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyautogui = "^0.9.48"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
flake8 = {version = "^3.7", allows-prereleases = true}
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
