[tool.poetry]
name = "nuggan"
version = "0.1.0"
description = "A library for creating self-aware ids"
authors = ["Kevin Schiroo <kjschiroo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
watchdog = "^0.9.0"
pytest-cov = "^2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
