# -*- coding: utf-8 -*-
from __future__ import division
from __future__ import print_function

DOM_KIND_WINDOW = 0
DOM_KIND_SECTION = 1
DOM_KIND_DIV = 2
DOM_KIND_P = 3
DOM_KIND_SPAN = 4
DOM_KIND_FROM = 5
DOM_KIND_INPUT = 6

CSS_UNSET = 0
# display
DISPLAY_BLOCK = 1
DISPLAY_INLINE = 2
DISPLAY_INLINE_BLOCK = 3            # 暂不使用
# text-align
TEXT_ALIGN_CENTER = 1
TEXT_ALIGN_LEFT = 2
TEXT_ALIGN_RIGHT = 3
# text-decoration
TEXT_DECORATION_NONE = 1
TEXT_DECORATION_BLINK = 2
TEXT_DECORATION_UNDERLINE = 3
TEXT_DECORATION_LINE_THROUGH = 4
TEXT_DECORATION_OVERLINE = 5
# font-weight
FONT_WEIGHT_NORMAL = 1
FONT_WEIGHT_LIGHTER = 2
FONT_WEIGHT_BOLD = 3
# position
POSITION_STATIC = 1
POSITION_RELATIVE = 2
POSITION_ABSOLUTE = 3
POSITION_FIXED = 4
