[tool.poetry]
name = "hilale"
version = "0.1.2"
description = "A simple python utility to keep the mouse moving on the screen"
authors = ["rkshrksh <aarkaygautam@gmail.com>"]

license = "MIT"
readme = "README.md"
python = "^3.7"
homepage = "https://github.com/rkshrksh/Hilale"
repository = "https://github.com/rkshrksh/Hilale"
documentation = "https://github.com/rkshrksh/Hilale"

keywords = ["python", "utility", "mouse", "pyautogui"]

[tool.poetry.dependencies]
python = "^3.7"
pyautogui = "^0.9.48"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
flake8 = {version = "^3.7", allows-prereleases = true}
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
