from os.path import abspath, dirname

from setuptools import setup


LONG_DESCRIPTION = open(dirname(abspath(__file__)) + "/README.md", "r").read()


setup(
    name="boto3-stubs",
    version="0.2.6",
    packages=["boto3-stubs"],
    url="https://github.com/vemel/mypy_boto3",
    license="MIT License",
    author="Vlad Emelianov",
    author_email="vlad.emelianov.nz@gmail.com",
    description="Boto3 1.10.25 stubs powered by `mypy-boto3`.",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Environment :: Console",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: Implementation :: CPython",
        "Typing :: Typed",
    ],
    long_description=LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    package_data={"boto3-stubs": ["py.typed", "*.pyi", "*/*.pyi"]},
    install_requires=["mypy-boto3==0.2.6",],
    extras_require={
        "all": [
            "mypy-boto3-acm==0.2.6",
            "mypy-boto3-acm-pca==0.2.6",
            "mypy-boto3-alexaforbusiness==0.2.6",
            "mypy-boto3-amplify==0.2.6",
            "mypy-boto3-apigateway==0.2.6",
            "mypy-boto3-apigatewaymanagementapi==0.2.6",
            "mypy-boto3-apigatewayv2==0.2.6",
            "mypy-boto3-application-autoscaling==0.2.6",
            "mypy-boto3-application-insights==0.2.6",
            "mypy-boto3-appmesh==0.2.6",
            "mypy-boto3-appstream==0.2.6",
            "mypy-boto3-appsync==0.2.6",
            "mypy-boto3-athena==0.2.6",
            "mypy-boto3-autoscaling==0.2.6",
            "mypy-boto3-autoscaling-plans==0.2.6",
            "mypy-boto3-backup==0.2.6",
            "mypy-boto3-batch==0.2.6",
            "mypy-boto3-budgets==0.2.6",
            "mypy-boto3-ce==0.2.6",
            "mypy-boto3-chime==0.2.6",
            "mypy-boto3-cloud9==0.2.6",
            "mypy-boto3-clouddirectory==0.2.6",
            "mypy-boto3-cloudformation==0.2.6",
            "mypy-boto3-cloudfront==0.2.6",
            "mypy-boto3-cloudhsm==0.2.6",
            "mypy-boto3-cloudhsmv2==0.2.6",
            "mypy-boto3-cloudsearch==0.2.6",
            "mypy-boto3-cloudsearchdomain==0.2.6",
            "mypy-boto3-cloudtrail==0.2.6",
            "mypy-boto3-cloudwatch==0.2.6",
            "mypy-boto3-codebuild==0.2.6",
            "mypy-boto3-codecommit==0.2.6",
            "mypy-boto3-codedeploy==0.2.6",
            "mypy-boto3-codepipeline==0.2.6",
            "mypy-boto3-codestar==0.2.6",
            "mypy-boto3-codestar-notifications==0.2.6",
            "mypy-boto3-cognito-identity==0.2.6",
            "mypy-boto3-cognito-idp==0.2.6",
            "mypy-boto3-cognito-sync==0.2.6",
            "mypy-boto3-comprehend==0.2.6",
            "mypy-boto3-comprehendmedical==0.2.6",
            "mypy-boto3-config==0.2.6",
            "mypy-boto3-connect==0.2.6",
            "mypy-boto3-cur==0.2.6",
            "mypy-boto3-datapipeline==0.2.6",
            "mypy-boto3-datasync==0.2.6",
            "mypy-boto3-dax==0.2.6",
            "mypy-boto3-devicefarm==0.2.6",
            "mypy-boto3-directconnect==0.2.6",
            "mypy-boto3-discovery==0.2.6",
            "mypy-boto3-dlm==0.2.6",
            "mypy-boto3-dms==0.2.6",
            "mypy-boto3-docdb==0.2.6",
            "mypy-boto3-ds==0.2.6",
            "mypy-boto3-dynamodb==0.2.6",
            "mypy-boto3-dynamodbstreams==0.2.6",
            "mypy-boto3-ec2==0.2.6",
            "mypy-boto3-ec2-instance-connect==0.2.6",
            "mypy-boto3-ecr==0.2.6",
            "mypy-boto3-ecs==0.2.6",
            "mypy-boto3-efs==0.2.6",
            "mypy-boto3-eks==0.2.6",
            "mypy-boto3-elasticache==0.2.6",
            "mypy-boto3-elasticbeanstalk==0.2.6",
            "mypy-boto3-elastictranscoder==0.2.6",
            "mypy-boto3-elb==0.2.6",
            "mypy-boto3-elbv2==0.2.6",
            "mypy-boto3-emr==0.2.6",
            "mypy-boto3-es==0.2.6",
            "mypy-boto3-events==0.2.6",
            "mypy-boto3-firehose==0.2.6",
            "mypy-boto3-fms==0.2.6",
            "mypy-boto3-forecast==0.2.6",
            "mypy-boto3-forecastquery==0.2.6",
            "mypy-boto3-fsx==0.2.6",
            "mypy-boto3-gamelift==0.2.6",
            "mypy-boto3-glacier==0.2.6",
            "mypy-boto3-globalaccelerator==0.2.6",
            "mypy-boto3-glue==0.2.6",
            "mypy-boto3-greengrass==0.2.6",
            "mypy-boto3-groundstation==0.2.6",
            "mypy-boto3-guardduty==0.2.6",
            "mypy-boto3-health==0.2.6",
            "mypy-boto3-iam==0.2.6",
            "mypy-boto3-importexport==0.2.6",
            "mypy-boto3-inspector==0.2.6",
            "mypy-boto3-iot==0.2.6",
            "mypy-boto3-iot-data==0.2.6",
            "mypy-boto3-iot-jobs-data==0.2.6",
            "mypy-boto3-iot1click-devices==0.2.6",
            "mypy-boto3-iot1click-projects==0.2.6",
            "mypy-boto3-iotanalytics==0.2.6",
            "mypy-boto3-iotevents==0.2.6",
            "mypy-boto3-iotevents-data==0.2.6",
            "mypy-boto3-iotthingsgraph==0.2.6",
            "mypy-boto3-kafka==0.2.6",
            "mypy-boto3-kinesis==0.2.6",
            "mypy-boto3-kinesis-video-archived-media==0.2.6",
            "mypy-boto3-kinesis-video-media==0.2.6",
            "mypy-boto3-kinesisanalytics==0.2.6",
            "mypy-boto3-kinesisanalyticsv2==0.2.6",
            "mypy-boto3-kinesisvideo==0.2.6",
            "mypy-boto3-kms==0.2.6",
            "mypy-boto3-lakeformation==0.2.6",
            "mypy-boto3-lambda==0.2.6",
            "mypy-boto3-lex-models==0.2.6",
            "mypy-boto3-lex-runtime==0.2.6",
            "mypy-boto3-license-manager==0.2.6",
            "mypy-boto3-lightsail==0.2.6",
            "mypy-boto3-logs==0.2.6",
            "mypy-boto3-machinelearning==0.2.6",
            "mypy-boto3-macie==0.2.6",
            "mypy-boto3-managedblockchain==0.2.6",
            "mypy-boto3-marketplace-entitlement==0.2.6",
            "mypy-boto3-marketplacecommerceanalytics==0.2.6",
            "mypy-boto3-mediaconnect==0.2.6",
            "mypy-boto3-mediaconvert==0.2.6",
            "mypy-boto3-medialive==0.2.6",
            "mypy-boto3-mediapackage==0.2.6",
            "mypy-boto3-mediapackage-vod==0.2.6",
            "mypy-boto3-mediastore==0.2.6",
            "mypy-boto3-mediastore-data==0.2.6",
            "mypy-boto3-mediatailor==0.2.6",
            "mypy-boto3-meteringmarketplace==0.2.6",
            "mypy-boto3-mgh==0.2.6",
            "mypy-boto3-mobile==0.2.6",
            "mypy-boto3-mq==0.2.6",
            "mypy-boto3-mturk==0.2.6",
            "mypy-boto3-neptune==0.2.6",
            "mypy-boto3-opsworks==0.2.6",
            "mypy-boto3-opsworkscm==0.2.6",
            "mypy-boto3-organizations==0.2.6",
            "mypy-boto3-personalize==0.2.6",
            "mypy-boto3-personalize-events==0.2.6",
            "mypy-boto3-personalize-runtime==0.2.6",
            "mypy-boto3-pi==0.2.6",
            "mypy-boto3-pinpoint==0.2.6",
            "mypy-boto3-pinpoint-email==0.2.6",
            "mypy-boto3-pinpoint-sms-voice==0.2.6",
            "mypy-boto3-polly==0.2.6",
            "mypy-boto3-pricing==0.2.6",
            "mypy-boto3-qldb==0.2.6",
            "mypy-boto3-qldb-session==0.2.6",
            "mypy-boto3-quicksight==0.2.6",
            "mypy-boto3-ram==0.2.6",
            "mypy-boto3-rds==0.2.6",
            "mypy-boto3-rds-data==0.2.6",
            "mypy-boto3-redshift==0.2.6",
            "mypy-boto3-rekognition==0.2.6",
            "mypy-boto3-resource-groups==0.2.6",
            "mypy-boto3-resourcegroupstaggingapi==0.2.6",
            "mypy-boto3-robomaker==0.2.6",
            "mypy-boto3-route53==0.2.6",
            "mypy-boto3-route53domains==0.2.6",
            "mypy-boto3-route53resolver==0.2.6",
            "mypy-boto3-s3==0.2.6",
            "mypy-boto3-s3control==0.2.6",
            "mypy-boto3-sagemaker==0.2.6",
            "mypy-boto3-sagemaker-runtime==0.2.6",
            "mypy-boto3-savingsplans==0.2.6",
            "mypy-boto3-sdb==0.2.6",
            "mypy-boto3-secretsmanager==0.2.6",
            "mypy-boto3-securityhub==0.2.6",
            "mypy-boto3-serverlessrepo==0.2.6",
            "mypy-boto3-service-quotas==0.2.6",
            "mypy-boto3-servicecatalog==0.2.6",
            "mypy-boto3-servicediscovery==0.2.6",
            "mypy-boto3-ses==0.2.6",
            "mypy-boto3-shield==0.2.6",
            "mypy-boto3-signer==0.2.6",
            "mypy-boto3-sms==0.2.6",
            "mypy-boto3-sms-voice==0.2.6",
            "mypy-boto3-snowball==0.2.6",
            "mypy-boto3-sns==0.2.6",
            "mypy-boto3-sqs==0.2.6",
            "mypy-boto3-ssm==0.2.6",
            "mypy-boto3-stepfunctions==0.2.6",
            "mypy-boto3-storagegateway==0.2.6",
            "mypy-boto3-sts==0.2.6",
            "mypy-boto3-support==0.2.6",
            "mypy-boto3-swf==0.2.6",
            "mypy-boto3-textract==0.2.6",
            "mypy-boto3-transcribe==0.2.6",
            "mypy-boto3-transfer==0.2.6",
            "mypy-boto3-translate==0.2.6",
            "mypy-boto3-waf==0.2.6",
            "mypy-boto3-waf-regional==0.2.6",
            "mypy-boto3-workdocs==0.2.6",
            "mypy-boto3-worklink==0.2.6",
            "mypy-boto3-workmail==0.2.6",
            "mypy-boto3-workmailmessageflow==0.2.6",
            "mypy-boto3-workspaces==0.2.6",
            "mypy-boto3-xray==0.2.6",
        ],
        "essential": [
            "mypy-boto3-cloudformation==0.2.6",
            "mypy-boto3-dynamodb==0.2.6",
            "mypy-boto3-ec2==0.2.6",
            "mypy-boto3-lambda==0.2.6",
            "mypy-boto3-rds==0.2.6",
            "mypy-boto3-s3==0.2.6",
            "mypy-boto3-sqs==0.2.6",
        ],
        "acm": ["mypy-boto3-acm==0.2.6"],
        "acm-pca": ["mypy-boto3-acm-pca==0.2.6"],
        "alexaforbusiness": ["mypy-boto3-alexaforbusiness==0.2.6"],
        "amplify": ["mypy-boto3-amplify==0.2.6"],
        "apigateway": ["mypy-boto3-apigateway==0.2.6"],
        "apigatewaymanagementapi": ["mypy-boto3-apigatewaymanagementapi==0.2.6"],
        "apigatewayv2": ["mypy-boto3-apigatewayv2==0.2.6"],
        "application-autoscaling": ["mypy-boto3-application-autoscaling==0.2.6"],
        "application-insights": ["mypy-boto3-application-insights==0.2.6"],
        "appmesh": ["mypy-boto3-appmesh==0.2.6"],
        "appstream": ["mypy-boto3-appstream==0.2.6"],
        "appsync": ["mypy-boto3-appsync==0.2.6"],
        "athena": ["mypy-boto3-athena==0.2.6"],
        "autoscaling": ["mypy-boto3-autoscaling==0.2.6"],
        "autoscaling-plans": ["mypy-boto3-autoscaling-plans==0.2.6"],
        "backup": ["mypy-boto3-backup==0.2.6"],
        "batch": ["mypy-boto3-batch==0.2.6"],
        "budgets": ["mypy-boto3-budgets==0.2.6"],
        "ce": ["mypy-boto3-ce==0.2.6"],
        "chime": ["mypy-boto3-chime==0.2.6"],
        "cloud9": ["mypy-boto3-cloud9==0.2.6"],
        "clouddirectory": ["mypy-boto3-clouddirectory==0.2.6"],
        "cloudformation": ["mypy-boto3-cloudformation==0.2.6"],
        "cloudfront": ["mypy-boto3-cloudfront==0.2.6"],
        "cloudhsm": ["mypy-boto3-cloudhsm==0.2.6"],
        "cloudhsmv2": ["mypy-boto3-cloudhsmv2==0.2.6"],
        "cloudsearch": ["mypy-boto3-cloudsearch==0.2.6"],
        "cloudsearchdomain": ["mypy-boto3-cloudsearchdomain==0.2.6"],
        "cloudtrail": ["mypy-boto3-cloudtrail==0.2.6"],
        "cloudwatch": ["mypy-boto3-cloudwatch==0.2.6"],
        "codebuild": ["mypy-boto3-codebuild==0.2.6"],
        "codecommit": ["mypy-boto3-codecommit==0.2.6"],
        "codedeploy": ["mypy-boto3-codedeploy==0.2.6"],
        "codepipeline": ["mypy-boto3-codepipeline==0.2.6"],
        "codestar": ["mypy-boto3-codestar==0.2.6"],
        "codestar-notifications": ["mypy-boto3-codestar-notifications==0.2.6"],
        "cognito-identity": ["mypy-boto3-cognito-identity==0.2.6"],
        "cognito-idp": ["mypy-boto3-cognito-idp==0.2.6"],
        "cognito-sync": ["mypy-boto3-cognito-sync==0.2.6"],
        "comprehend": ["mypy-boto3-comprehend==0.2.6"],
        "comprehendmedical": ["mypy-boto3-comprehendmedical==0.2.6"],
        "config": ["mypy-boto3-config==0.2.6"],
        "connect": ["mypy-boto3-connect==0.2.6"],
        "cur": ["mypy-boto3-cur==0.2.6"],
        "datapipeline": ["mypy-boto3-datapipeline==0.2.6"],
        "datasync": ["mypy-boto3-datasync==0.2.6"],
        "dax": ["mypy-boto3-dax==0.2.6"],
        "devicefarm": ["mypy-boto3-devicefarm==0.2.6"],
        "directconnect": ["mypy-boto3-directconnect==0.2.6"],
        "discovery": ["mypy-boto3-discovery==0.2.6"],
        "dlm": ["mypy-boto3-dlm==0.2.6"],
        "dms": ["mypy-boto3-dms==0.2.6"],
        "docdb": ["mypy-boto3-docdb==0.2.6"],
        "ds": ["mypy-boto3-ds==0.2.6"],
        "dynamodb": ["mypy-boto3-dynamodb==0.2.6"],
        "dynamodbstreams": ["mypy-boto3-dynamodbstreams==0.2.6"],
        "ec2": ["mypy-boto3-ec2==0.2.6"],
        "ec2-instance-connect": ["mypy-boto3-ec2-instance-connect==0.2.6"],
        "ecr": ["mypy-boto3-ecr==0.2.6"],
        "ecs": ["mypy-boto3-ecs==0.2.6"],
        "efs": ["mypy-boto3-efs==0.2.6"],
        "eks": ["mypy-boto3-eks==0.2.6"],
        "elasticache": ["mypy-boto3-elasticache==0.2.6"],
        "elasticbeanstalk": ["mypy-boto3-elasticbeanstalk==0.2.6"],
        "elastictranscoder": ["mypy-boto3-elastictranscoder==0.2.6"],
        "elb": ["mypy-boto3-elb==0.2.6"],
        "elbv2": ["mypy-boto3-elbv2==0.2.6"],
        "emr": ["mypy-boto3-emr==0.2.6"],
        "es": ["mypy-boto3-es==0.2.6"],
        "events": ["mypy-boto3-events==0.2.6"],
        "firehose": ["mypy-boto3-firehose==0.2.6"],
        "fms": ["mypy-boto3-fms==0.2.6"],
        "forecast": ["mypy-boto3-forecast==0.2.6"],
        "forecastquery": ["mypy-boto3-forecastquery==0.2.6"],
        "fsx": ["mypy-boto3-fsx==0.2.6"],
        "gamelift": ["mypy-boto3-gamelift==0.2.6"],
        "glacier": ["mypy-boto3-glacier==0.2.6"],
        "globalaccelerator": ["mypy-boto3-globalaccelerator==0.2.6"],
        "glue": ["mypy-boto3-glue==0.2.6"],
        "greengrass": ["mypy-boto3-greengrass==0.2.6"],
        "groundstation": ["mypy-boto3-groundstation==0.2.6"],
        "guardduty": ["mypy-boto3-guardduty==0.2.6"],
        "health": ["mypy-boto3-health==0.2.6"],
        "iam": ["mypy-boto3-iam==0.2.6"],
        "importexport": ["mypy-boto3-importexport==0.2.6"],
        "inspector": ["mypy-boto3-inspector==0.2.6"],
        "iot": ["mypy-boto3-iot==0.2.6"],
        "iot-data": ["mypy-boto3-iot-data==0.2.6"],
        "iot-jobs-data": ["mypy-boto3-iot-jobs-data==0.2.6"],
        "iot1click-devices": ["mypy-boto3-iot1click-devices==0.2.6"],
        "iot1click-projects": ["mypy-boto3-iot1click-projects==0.2.6"],
        "iotanalytics": ["mypy-boto3-iotanalytics==0.2.6"],
        "iotevents": ["mypy-boto3-iotevents==0.2.6"],
        "iotevents-data": ["mypy-boto3-iotevents-data==0.2.6"],
        "iotthingsgraph": ["mypy-boto3-iotthingsgraph==0.2.6"],
        "kafka": ["mypy-boto3-kafka==0.2.6"],
        "kinesis": ["mypy-boto3-kinesis==0.2.6"],
        "kinesis-video-archived-media": [
            "mypy-boto3-kinesis-video-archived-media==0.2.6"
        ],
        "kinesis-video-media": ["mypy-boto3-kinesis-video-media==0.2.6"],
        "kinesisanalytics": ["mypy-boto3-kinesisanalytics==0.2.6"],
        "kinesisanalyticsv2": ["mypy-boto3-kinesisanalyticsv2==0.2.6"],
        "kinesisvideo": ["mypy-boto3-kinesisvideo==0.2.6"],
        "kms": ["mypy-boto3-kms==0.2.6"],
        "lakeformation": ["mypy-boto3-lakeformation==0.2.6"],
        "lambda": ["mypy-boto3-lambda==0.2.6"],
        "lex-models": ["mypy-boto3-lex-models==0.2.6"],
        "lex-runtime": ["mypy-boto3-lex-runtime==0.2.6"],
        "license-manager": ["mypy-boto3-license-manager==0.2.6"],
        "lightsail": ["mypy-boto3-lightsail==0.2.6"],
        "logs": ["mypy-boto3-logs==0.2.6"],
        "machinelearning": ["mypy-boto3-machinelearning==0.2.6"],
        "macie": ["mypy-boto3-macie==0.2.6"],
        "managedblockchain": ["mypy-boto3-managedblockchain==0.2.6"],
        "marketplace-entitlement": ["mypy-boto3-marketplace-entitlement==0.2.6"],
        "marketplacecommerceanalytics": [
            "mypy-boto3-marketplacecommerceanalytics==0.2.6"
        ],
        "mediaconnect": ["mypy-boto3-mediaconnect==0.2.6"],
        "mediaconvert": ["mypy-boto3-mediaconvert==0.2.6"],
        "medialive": ["mypy-boto3-medialive==0.2.6"],
        "mediapackage": ["mypy-boto3-mediapackage==0.2.6"],
        "mediapackage-vod": ["mypy-boto3-mediapackage-vod==0.2.6"],
        "mediastore": ["mypy-boto3-mediastore==0.2.6"],
        "mediastore-data": ["mypy-boto3-mediastore-data==0.2.6"],
        "mediatailor": ["mypy-boto3-mediatailor==0.2.6"],
        "meteringmarketplace": ["mypy-boto3-meteringmarketplace==0.2.6"],
        "mgh": ["mypy-boto3-mgh==0.2.6"],
        "mobile": ["mypy-boto3-mobile==0.2.6"],
        "mq": ["mypy-boto3-mq==0.2.6"],
        "mturk": ["mypy-boto3-mturk==0.2.6"],
        "neptune": ["mypy-boto3-neptune==0.2.6"],
        "opsworks": ["mypy-boto3-opsworks==0.2.6"],
        "opsworkscm": ["mypy-boto3-opsworkscm==0.2.6"],
        "organizations": ["mypy-boto3-organizations==0.2.6"],
        "personalize": ["mypy-boto3-personalize==0.2.6"],
        "personalize-events": ["mypy-boto3-personalize-events==0.2.6"],
        "personalize-runtime": ["mypy-boto3-personalize-runtime==0.2.6"],
        "pi": ["mypy-boto3-pi==0.2.6"],
        "pinpoint": ["mypy-boto3-pinpoint==0.2.6"],
        "pinpoint-email": ["mypy-boto3-pinpoint-email==0.2.6"],
        "pinpoint-sms-voice": ["mypy-boto3-pinpoint-sms-voice==0.2.6"],
        "polly": ["mypy-boto3-polly==0.2.6"],
        "pricing": ["mypy-boto3-pricing==0.2.6"],
        "qldb": ["mypy-boto3-qldb==0.2.6"],
        "qldb-session": ["mypy-boto3-qldb-session==0.2.6"],
        "quicksight": ["mypy-boto3-quicksight==0.2.6"],
        "ram": ["mypy-boto3-ram==0.2.6"],
        "rds": ["mypy-boto3-rds==0.2.6"],
        "rds-data": ["mypy-boto3-rds-data==0.2.6"],
        "redshift": ["mypy-boto3-redshift==0.2.6"],
        "rekognition": ["mypy-boto3-rekognition==0.2.6"],
        "resource-groups": ["mypy-boto3-resource-groups==0.2.6"],
        "resourcegroupstaggingapi": ["mypy-boto3-resourcegroupstaggingapi==0.2.6"],
        "robomaker": ["mypy-boto3-robomaker==0.2.6"],
        "route53": ["mypy-boto3-route53==0.2.6"],
        "route53domains": ["mypy-boto3-route53domains==0.2.6"],
        "route53resolver": ["mypy-boto3-route53resolver==0.2.6"],
        "s3": ["mypy-boto3-s3==0.2.6"],
        "s3control": ["mypy-boto3-s3control==0.2.6"],
        "sagemaker": ["mypy-boto3-sagemaker==0.2.6"],
        "sagemaker-runtime": ["mypy-boto3-sagemaker-runtime==0.2.6"],
        "savingsplans": ["mypy-boto3-savingsplans==0.2.6"],
        "sdb": ["mypy-boto3-sdb==0.2.6"],
        "secretsmanager": ["mypy-boto3-secretsmanager==0.2.6"],
        "securityhub": ["mypy-boto3-securityhub==0.2.6"],
        "serverlessrepo": ["mypy-boto3-serverlessrepo==0.2.6"],
        "service-quotas": ["mypy-boto3-service-quotas==0.2.6"],
        "servicecatalog": ["mypy-boto3-servicecatalog==0.2.6"],
        "servicediscovery": ["mypy-boto3-servicediscovery==0.2.6"],
        "ses": ["mypy-boto3-ses==0.2.6"],
        "shield": ["mypy-boto3-shield==0.2.6"],
        "signer": ["mypy-boto3-signer==0.2.6"],
        "sms": ["mypy-boto3-sms==0.2.6"],
        "sms-voice": ["mypy-boto3-sms-voice==0.2.6"],
        "snowball": ["mypy-boto3-snowball==0.2.6"],
        "sns": ["mypy-boto3-sns==0.2.6"],
        "sqs": ["mypy-boto3-sqs==0.2.6"],
        "ssm": ["mypy-boto3-ssm==0.2.6"],
        "stepfunctions": ["mypy-boto3-stepfunctions==0.2.6"],
        "storagegateway": ["mypy-boto3-storagegateway==0.2.6"],
        "sts": ["mypy-boto3-sts==0.2.6"],
        "support": ["mypy-boto3-support==0.2.6"],
        "swf": ["mypy-boto3-swf==0.2.6"],
        "textract": ["mypy-boto3-textract==0.2.6"],
        "transcribe": ["mypy-boto3-transcribe==0.2.6"],
        "transfer": ["mypy-boto3-transfer==0.2.6"],
        "translate": ["mypy-boto3-translate==0.2.6"],
        "waf": ["mypy-boto3-waf==0.2.6"],
        "waf-regional": ["mypy-boto3-waf-regional==0.2.6"],
        "workdocs": ["mypy-boto3-workdocs==0.2.6"],
        "worklink": ["mypy-boto3-worklink==0.2.6"],
        "workmail": ["mypy-boto3-workmail==0.2.6"],
        "workmailmessageflow": ["mypy-boto3-workmailmessageflow==0.2.6"],
        "workspaces": ["mypy-boto3-workspaces==0.2.6"],
        "xray": ["mypy-boto3-xray==0.2.6"],
    },
    zip_safe=False,
)
