
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-25T21:33:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bac4e2a7bd5fc33aee1adac5f54b2f3e644ae89b",
 "version": "0.4.2rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
