
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-18T17:32:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "83772c8b9374971acf8f2b7d119d30d71b1d3972",
 "version": "0.7.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
