# Generated by Django 2.2.7 on 2019-11-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localcosmos_server', '0003_auto_20191112_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='webapp_zip_url',
            new_name='pwa_zip_url',
        ),
    ]
