[tool.poetry]
name = "grpug-poetry-demo"
version = "0.1.0"
description = ""
authors = ["Jace Browning <jacebrowning@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.4"
django = "^2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
