[tool.poetry]
name = "nose-gevent-monkey"
version = "0.1.0"
description = "A nose plugin to monkey patch gevent as early as possible"
authors = ["BCD Trip Tech <development@bcdtriptech.com>"]

[tool.poetry.dependencies]
python = "^3.6"
nose = "*"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."nose.plugins"]
gevent-monkey = "nose_gevent_monkey:GeventMonkey"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
