- name: Deploy QULo
  hosts: fuchs-master
  vars:
    qulo_conf: "/etc/qulo"
    
  tasks:
  - name: Install Python 3.6
    yum:
      name:
        - python36.x86_64
        - python36-devel.x86_64
      state: present

  - name: Install QULo
    pip:
      name: QULo
      virtualenv: /cm/shared/admintools/QULo
      virtualenv_command: "/usr/bin/pyvenv-3.6"

  - name: Create configuration directory
    file:
      path: "{{ qulo_conf }}"
      state: directory

  - name: Copy configuration files
    copy:
      src: "{{ item }}"
      dest: "{{ qulo_conf }}"
    with_items:
      - qagent.conf
      - qmaster.conf
