- name: Provisioning infrastructure for QULo on nodes
  hosts: "{{ restricted_hosts | default('fuchs-compute-nodes') }}"
  vars:
    qulo_conf: "/etc/qulo"
    
  tasks:
  - name: Install Python 3.6 (yum)
    yum:
      name:
        - python36.x86_64
        - python36-devel.x86_64
      state: present

  - name: Create configuration directory
    file:
      path: "{{ qulo_conf }}"
      state: directory

  - name: Copy configuration files
    copy:
      src: "{{ item }}"
      dest: "{{ qulo_conf }}"
    with_items:
      - qagent.conf
