[tool.poetry]
name = "neeraj-poetry-demo"
version = "0.1.0"
description = ""
authors = ["Neeraj Chaudhary <neeraj_chaudhary@mcafee.com>"]

[tool.poetry.dependencies]
python = "^2.7"
pendulum = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
