# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bulk_update_firmware.ui'
#
# Created: Tue Oct  8 16:06:57 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_BulkUpdateFirmwareDialog(object):
    def setupUi(self, BulkUpdateFirmwareDialog):
        BulkUpdateFirmwareDialog.setObjectName("BulkUpdateFirmwareDialog")
        BulkUpdateFirmwareDialog.resize(387, 262)
        self.gridLayout = QtGui.QGridLayout(BulkUpdateFirmwareDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.firmwareLabel = QtGui.QLabel(BulkUpdateFirmwareDialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.firmwareLabel.setFont(font)
        self.firmwareLabel.setObjectName("firmwareLabel")
        self.gridLayout.addWidget(self.firmwareLabel, 0, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.firmwareLocation = QtGui.QLineEdit(BulkUpdateFirmwareDialog)
        self.firmwareLocation.setObjectName("firmwareLocation")
        self.horizontalLayout.addWidget(self.firmwareLocation)
        self.browseButton = QtGui.QPushButton(BulkUpdateFirmwareDialog)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 3)
        self.serialRangeLabel = QtGui.QLabel(BulkUpdateFirmwareDialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.serialRangeLabel.setFont(font)
        self.serialRangeLabel.setObjectName("serialRangeLabel")
        self.gridLayout.addWidget(self.serialRangeLabel, 2, 0, 1, 4)
        self.minSerialLabel = QtGui.QLabel(BulkUpdateFirmwareDialog)
        self.minSerialLabel.setObjectName("minSerialLabel")
        self.gridLayout.addWidget(self.minSerialLabel, 3, 1, 1, 2)
        self.minSerial = QtGui.QSpinBox(BulkUpdateFirmwareDialog)
        self.minSerial.setMaximum(2147483647)
        self.minSerial.setObjectName("minSerial")
        self.gridLayout.addWidget(self.minSerial, 3, 3, 1, 1)
        self.maxSerialLabel = QtGui.QLabel(BulkUpdateFirmwareDialog)
        self.maxSerialLabel.setObjectName("maxSerialLabel")
        self.gridLayout.addWidget(self.maxSerialLabel, 4, 1, 1, 2)
        self.maxSerial = QtGui.QSpinBox(BulkUpdateFirmwareDialog)
        self.maxSerial.setMaximum(2147483647)
        self.maxSerial.setProperty("value", 2147483647)
        self.maxSerial.setObjectName("maxSerial")
        self.gridLayout.addWidget(self.maxSerial, 4, 3, 1, 1)
        self.setDeviceModeLabel = QtGui.QLabel(BulkUpdateFirmwareDialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.setDeviceModeLabel.setFont(font)
        self.setDeviceModeLabel.setObjectName("setDeviceModeLabel")
        self.gridLayout.addWidget(self.setDeviceModeLabel, 6, 0, 1, 4)
        self.setDeviceMode = QtGui.QCheckBox(BulkUpdateFirmwareDialog)
        self.setDeviceMode.setObjectName("setDeviceMode")
        self.gridLayout.addWidget(self.setDeviceMode, 7, 1, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 1, 1, 1)
        self.deviceModeLabel = QtGui.QLabel(BulkUpdateFirmwareDialog)
        self.deviceModeLabel.setEnabled(False)
        self.deviceModeLabel.setObjectName("deviceModeLabel")
        self.gridLayout.addWidget(self.deviceModeLabel, 8, 2, 1, 1)
        self.deviceMode = QtGui.QSpinBox(BulkUpdateFirmwareDialog)
        self.deviceMode.setEnabled(False)
        self.deviceMode.setMaximum(255)
        self.deviceMode.setProperty("value", 2)
        self.deviceMode.setObjectName("deviceMode")
        self.gridLayout.addWidget(self.deviceMode, 8, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(369, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(BulkUpdateFirmwareDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 0, 1, 4)
        self.radioStrengthLabel = QtGui.QLabel(BulkUpdateFirmwareDialog)
        self.radioStrengthLabel.setObjectName("radioStrengthLabel")
        self.gridLayout.addWidget(self.radioStrengthLabel, 5, 1, 1, 2)
        self.radioStrength = QtGui.QSpinBox(BulkUpdateFirmwareDialog)
        self.radioStrength.setMinimum(-100)
        self.radioStrength.setMaximum(0)
        self.radioStrength.setProperty("value", -100)
        self.radioStrength.setObjectName("radioStrength")
        self.gridLayout.addWidget(self.radioStrength, 5, 3, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)

        self.retranslateUi(BulkUpdateFirmwareDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), BulkUpdateFirmwareDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), BulkUpdateFirmwareDialog.reject)
        QtCore.QObject.connect(self.setDeviceMode, QtCore.SIGNAL("toggled(bool)"), self.deviceModeLabel.setEnabled)
        QtCore.QObject.connect(self.setDeviceMode, QtCore.SIGNAL("toggled(bool)"), self.deviceMode.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(BulkUpdateFirmwareDialog)
        BulkUpdateFirmwareDialog.setTabOrder(self.firmwareLocation, self.browseButton)
        BulkUpdateFirmwareDialog.setTabOrder(self.browseButton, self.minSerial)
        BulkUpdateFirmwareDialog.setTabOrder(self.minSerial, self.maxSerial)
        BulkUpdateFirmwareDialog.setTabOrder(self.maxSerial, self.setDeviceMode)
        BulkUpdateFirmwareDialog.setTabOrder(self.setDeviceMode, self.deviceMode)
        BulkUpdateFirmwareDialog.setTabOrder(self.deviceMode, self.buttonBox)

    def retranslateUi(self, BulkUpdateFirmwareDialog):
        BulkUpdateFirmwareDialog.setWindowTitle(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Bulk Update Firmware", None, QtGui.QApplication.UnicodeUTF8))
        self.firmwareLabel.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Firmware", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.serialRangeLabel.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Device Filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.minSerialLabel.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Minimum SN", None, QtGui.QApplication.UnicodeUTF8))
        self.maxSerialLabel.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Maximum SN", None, QtGui.QApplication.UnicodeUTF8))
        self.setDeviceModeLabel.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Set Device Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.setDeviceMode.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Set Device Mode After Update", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceModeLabel.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Device Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radioStrengthLabel.setText(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", "Minimum Radio Strength", None, QtGui.QApplication.UnicodeUTF8))
        self.radioStrength.setSuffix(QtGui.QApplication.translate("BulkUpdateFirmwareDialog", " dBm", None, QtGui.QApplication.UnicodeUTF8))

