# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_tab.ui'
#
# Created: Fri Oct 11 16:08:08 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DeviceTab(object):
    def setupUi(self, DeviceTab):
        DeviceTab.setObjectName("DeviceTab")
        DeviceTab.resize(1004, 600)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DeviceTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.graphChannelComboBox = QtGui.QComboBox(DeviceTab)
        self.graphChannelComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.graphChannelComboBox.setMaxVisibleItems(20)
        self.graphChannelComboBox.setObjectName("graphChannelComboBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.graphChannelComboBox)
        self.graphChannelLabel = QtGui.QLabel(DeviceTab)
        self.graphChannelLabel.setObjectName("graphChannelLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.graphChannelLabel)
        self.fftSubchannelComboBox = QtGui.QComboBox(DeviceTab)
        self.fftSubchannelComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.fftSubchannelComboBox.setMaxVisibleItems(20)
        self.fftSubchannelComboBox.setObjectName("fftSubchannelComboBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.fftSubchannelComboBox)
        self.fftSubchannelLabel = QtGui.QLabel(DeviceTab)
        self.fftSubchannelLabel.setObjectName("fftSubchannelLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.fftSubchannelLabel)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.serialNumberLabel = QtGui.QLabel(DeviceTab)
        self.serialNumberLabel.setObjectName("serialNumberLabel")
        self.gridLayout.addWidget(self.serialNumberLabel, 0, 0, 1, 1)
        self.userTag2 = QtGui.QLabel(DeviceTab)
        self.userTag2.setObjectName("userTag2")
        self.gridLayout.addWidget(self.userTag2, 2, 1, 1, 1)
        self.userTag1 = QtGui.QLabel(DeviceTab)
        self.userTag1.setObjectName("userTag1")
        self.gridLayout.addWidget(self.userTag1, 1, 1, 1, 1)
        self.userTag2Label = QtGui.QLabel(DeviceTab)
        self.userTag2Label.setObjectName("userTag2Label")
        self.gridLayout.addWidget(self.userTag2Label, 2, 0, 1, 1)
        self.serialNumber = QtGui.QLabel(DeviceTab)
        self.serialNumber.setObjectName("serialNumber")
        self.gridLayout.addWidget(self.serialNumber, 0, 1, 1, 1)
        self.userTag1Label = QtGui.QLabel(DeviceTab)
        self.userTag1Label.setObjectName("userTag1Label")
        self.gridLayout.addWidget(self.userTag1Label, 1, 0, 1, 1)
        self.boardInfoLabel = QtGui.QLabel(DeviceTab)
        self.boardInfoLabel.setObjectName("boardInfoLabel")
        self.gridLayout.addWidget(self.boardInfoLabel, 0, 3, 1, 1)
        self.boardInfo = QtGui.QLabel(DeviceTab)
        self.boardInfo.setObjectName("boardInfo")
        self.gridLayout.addWidget(self.boardInfo, 0, 4, 1, 1)
        self.buildInfoLabel = QtGui.QLabel(DeviceTab)
        self.buildInfoLabel.setObjectName("buildInfoLabel")
        self.gridLayout.addWidget(self.buildInfoLabel, 1, 3, 1, 1)
        self.buildInfo = QtGui.QLabel(DeviceTab)
        self.buildInfo.setObjectName("buildInfo")
        self.gridLayout.addWidget(self.buildInfo, 1, 4, 1, 1)
        self.buildDateLabel = QtGui.QLabel(DeviceTab)
        self.buildDateLabel.setObjectName("buildDateLabel")
        self.gridLayout.addWidget(self.buildDateLabel, 2, 3, 1, 1)
        self.buildDate = QtGui.QLabel(DeviceTab)
        self.buildDate.setObjectName("buildDate")
        self.gridLayout.addWidget(self.buildDate, 2, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 5, 1, 1)
        self.bootloaderIndicator = QtGui.QLabel(DeviceTab)
        self.bootloaderIndicator.setStyleSheet("QLabel { background-color : yellow ; font-weight : bold ; font-size : 12px ; }")
        self.bootloaderIndicator.setMargin(10)
        self.bootloaderIndicator.setObjectName("bootloaderIndicator")
        self.gridLayout.addWidget(self.bootloaderIndicator, 0, 6, 3, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.closeButton = QtGui.QPushButton(DeviceTab)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)
        self.menuButton = QtGui.QPushButton(DeviceTab)
        self.menuButton.setEnabled(False)
        self.menuButton.setObjectName("menuButton")
        self.verticalLayout.addWidget(self.menuButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.stackedWidget = QtGui.QStackedWidget(DeviceTab)
        self.stackedWidget.setObjectName("stackedWidget")
        self.disconnectPage = QtGui.QWidget()
        self.disconnectPage.setObjectName("disconnectPage")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.disconnectPage)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.statusLabel = QtGui.QLabel(self.disconnectPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_3.addWidget(self.statusLabel)
        self.statusProgressBar = QtGui.QProgressBar(self.disconnectPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusProgressBar.sizePolicy().hasHeightForWidth())
        self.statusProgressBar.setSizePolicy(sizePolicy)
        self.statusProgressBar.setMinimumSize(QtCore.QSize(175, 0))
        self.statusProgressBar.setProperty("value", 24)
        self.statusProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.statusProgressBar.setObjectName("statusProgressBar")
        self.verticalLayout_3.addWidget(self.statusProgressBar)
        spacerItem6 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem7 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.disconnectPage)
        self.displayPage = QtGui.QWidget()
        self.displayPage.setObjectName("displayPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.displayPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.panelLayout = QtGui.QHBoxLayout()
        self.panelLayout.setObjectName("panelLayout")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsLayout = GraphicsLayoutWidget(self.displayPage)
        self.graphicsLayout.setObjectName("graphicsLayout")
        self.verticalLayout_4.addWidget(self.graphicsLayout)
        self.panelLayout.addLayout(self.verticalLayout_4)
        self.panelLayout.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.panelLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.channelGroupBox = QtGui.QGroupBox(self.displayPage)
        self.channelGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.channelGroupBox.setObjectName("channelGroupBox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.channelGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.channelLayout = QtGui.QGridLayout()
        self.channelLayout.setObjectName("channelLayout")
        self.meanLabel = QtGui.QLabel(self.channelGroupBox)
        self.meanLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.meanLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meanLabel.setObjectName("meanLabel")
        self.channelLayout.addWidget(self.meanLabel, 0, 1, 1, 1)
        self.samplingRateLabel = QtGui.QLabel(self.channelGroupBox)
        self.samplingRateLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.samplingRateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.samplingRateLabel.setObjectName("samplingRateLabel")
        self.channelLayout.addWidget(self.samplingRateLabel, 0, 3, 1, 1)
        self.stdDevLabel = QtGui.QLabel(self.channelGroupBox)
        self.stdDevLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.stdDevLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stdDevLabel.setObjectName("stdDevLabel")
        self.channelLayout.addWidget(self.stdDevLabel, 0, 2, 1, 1)
        self.channelLabel = QtGui.QLabel(self.channelGroupBox)
        self.channelLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.channelLabel.setText("")
        self.channelLabel.setObjectName("channelLabel")
        self.channelLayout.addWidget(self.channelLabel, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.channelLayout)
        spacerItem8 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.horizontalLayout_3.addWidget(self.channelGroupBox)
        self.LEDGroupBox = QtGui.QGroupBox(self.displayPage)
        self.LEDGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.LEDGroupBox.setObjectName("LEDGroupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.LEDGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LEDLayout = QtGui.QVBoxLayout()
        self.LEDLayout.setObjectName("LEDLayout")
        self.verticalLayout_7.addLayout(self.LEDLayout)
        spacerItem9 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_3.addWidget(self.LEDGroupBox)
        self.logGroupBox = QtGui.QGroupBox(self.displayPage)
        self.logGroupBox.setObjectName("logGroupBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.logGroupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.logList = QtGui.QListWidget(self.logGroupBox)
        self.logList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logList.setObjectName("logList")
        self.verticalLayout_9.addWidget(self.logList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.recentLostPacketsLabel = QtGui.QLabel(self.logGroupBox)
        self.recentLostPacketsLabel.setObjectName("recentLostPacketsLabel")
        self.horizontalLayout_2.addWidget(self.recentLostPacketsLabel)
        self.recentLostPackets = QtGui.QLineEdit(self.logGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recentLostPackets.sizePolicy().hasHeightForWidth())
        self.recentLostPackets.setSizePolicy(sizePolicy)
        self.recentLostPackets.setMaximumSize(QtCore.QSize(60, 16777215))
        self.recentLostPackets.setMaxLength(10)
        self.recentLostPackets.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.recentLostPackets.setReadOnly(True)
        self.recentLostPackets.setObjectName("recentLostPackets")
        self.horizontalLayout_2.addWidget(self.recentLostPackets)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.logGroupBox)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.setStretch(0, 1)
        self.stackedWidget.addWidget(self.displayPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.actionSetUserTag1 = QtGui.QAction(DeviceTab)
        self.actionSetUserTag1.setObjectName("actionSetUserTag1")
        self.actionSetUserTag2 = QtGui.QAction(DeviceTab)
        self.actionSetUserTag2.setObjectName("actionSetUserTag2")
        self.actionEditDeviceSettings = QtGui.QAction(DeviceTab)
        self.actionEditDeviceSettings.setObjectName("actionEditDeviceSettings")
        self.actionShowDeviceInfo = QtGui.QAction(DeviceTab)
        self.actionShowDeviceInfo.setObjectName("actionShowDeviceInfo")
        self.actionFirmwareLatestStable = QtGui.QAction(DeviceTab)
        self.actionFirmwareLatestStable.setEnabled(False)
        self.actionFirmwareLatestStable.setObjectName("actionFirmwareLatestStable")
        self.actionShowPacketStats = QtGui.QAction(DeviceTab)
        self.actionShowPacketStats.setObjectName("actionShowPacketStats")
        self.actionChangeActiveStreams = QtGui.QAction(DeviceTab)
        self.actionChangeActiveStreams.setObjectName("actionChangeActiveStreams")
        self.actionRunTests = QtGui.QAction(DeviceTab)
        self.actionRunTests.setObjectName("actionRunTests")
        self.actionSetDeviceMode = QtGui.QAction(DeviceTab)
        self.actionSetDeviceMode.setEnabled(False)
        self.actionSetDeviceMode.setObjectName("actionSetDeviceMode")
        self.actionFirmwareFromBranch = QtGui.QAction(DeviceTab)
        self.actionFirmwareFromBranch.setEnabled(False)
        self.actionFirmwareFromBranch.setObjectName("actionFirmwareFromBranch")
        self.actionFirmwareFromCommit = QtGui.QAction(DeviceTab)
        self.actionFirmwareFromCommit.setEnabled(False)
        self.actionFirmwareFromCommit.setObjectName("actionFirmwareFromCommit")
        self.actionFirmwareFromFile = QtGui.QAction(DeviceTab)
        self.actionFirmwareFromFile.setEnabled(False)
        self.actionFirmwareFromFile.setObjectName("actionFirmwareFromFile")
        self.actionForceRunBootloader = QtGui.QAction(DeviceTab)
        self.actionForceRunBootloader.setEnabled(False)
        self.actionForceRunBootloader.setObjectName("actionForceRunBootloader")
        self.actionForceRunApplication = QtGui.QAction(DeviceTab)
        self.actionForceRunApplication.setEnabled(False)
        self.actionForceRunApplication.setObjectName("actionForceRunApplication")
        self.actionForceReset = QtGui.QAction(DeviceTab)
        self.actionForceReset.setObjectName("actionForceReset")
        self.actionRaiseException = QtGui.QAction(DeviceTab)
        self.actionRaiseException.setObjectName("actionRaiseException")
        self.actionRecoverNVM = QtGui.QAction(DeviceTab)
        self.actionRecoverNVM.setObjectName("actionRecoverNVM")
        self.actionCalibrate = QtGui.QAction(DeviceTab)
        self.actionCalibrate.setCheckable(True)
        self.actionCalibrate.setEnabled(False)
        self.actionCalibrate.setObjectName("actionCalibrate")

        self.retranslateUi(DeviceTab)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DeviceTab)

    def retranslateUi(self, DeviceTab):
        DeviceTab.setWindowTitle(QtGui.QApplication.translate("DeviceTab", "Device Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.graphChannelLabel.setText(QtGui.QApplication.translate("DeviceTab", "Graph Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.fftSubchannelLabel.setText(QtGui.QApplication.translate("DeviceTab", "Frequency Subchannel:", None, QtGui.QApplication.UnicodeUTF8))
        self.serialNumberLabel.setText(QtGui.QApplication.translate("DeviceTab", "Serial Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.userTag2.setText(QtGui.QApplication.translate("DeviceTab", "User Tag 2", None, QtGui.QApplication.UnicodeUTF8))
        self.userTag1.setText(QtGui.QApplication.translate("DeviceTab", "User Tag 1", None, QtGui.QApplication.UnicodeUTF8))
        self.userTag2Label.setText(QtGui.QApplication.translate("DeviceTab", "User Tag 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.serialNumber.setText(QtGui.QApplication.translate("DeviceTab", "Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.userTag1Label.setText(QtGui.QApplication.translate("DeviceTab", "User Tag 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.boardInfoLabel.setText(QtGui.QApplication.translate("DeviceTab", "Board Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.boardInfo.setText(QtGui.QApplication.translate("DeviceTab", "Board Info", None, QtGui.QApplication.UnicodeUTF8))
        self.buildInfoLabel.setText(QtGui.QApplication.translate("DeviceTab", "Build Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.buildInfo.setText(QtGui.QApplication.translate("DeviceTab", "Build Info", None, QtGui.QApplication.UnicodeUTF8))
        self.buildDateLabel.setText(QtGui.QApplication.translate("DeviceTab", "Build Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.buildDate.setText(QtGui.QApplication.translate("DeviceTab", "Build Date", None, QtGui.QApplication.UnicodeUTF8))
        self.bootloaderIndicator.setText(QtGui.QApplication.translate("DeviceTab", "Bootloader", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("DeviceTab", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.menuButton.setText(QtGui.QApplication.translate("DeviceTab", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("DeviceTab", "Disconnected", None, QtGui.QApplication.UnicodeUTF8))
        self.channelGroupBox.setTitle(QtGui.QApplication.translate("DeviceTab", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.meanLabel.setText(QtGui.QApplication.translate("DeviceTab", "Mean (1s)", None, QtGui.QApplication.UnicodeUTF8))
        self.samplingRateLabel.setText(QtGui.QApplication.translate("DeviceTab", "Sampling Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.stdDevLabel.setText(QtGui.QApplication.translate("DeviceTab", "Std Dev (1s)", None, QtGui.QApplication.UnicodeUTF8))
        self.LEDGroupBox.setTitle(QtGui.QApplication.translate("DeviceTab", "LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.logGroupBox.setTitle(QtGui.QApplication.translate("DeviceTab", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.recentLostPacketsLabel.setText(QtGui.QApplication.translate("DeviceTab", "Lost Packets (last 20 s):", None, QtGui.QApplication.UnicodeUTF8))
        self.recentLostPackets.setText(QtGui.QApplication.translate("DeviceTab", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetUserTag1.setText(QtGui.QApplication.translate("DeviceTab", "Set User Tag 1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetUserTag2.setText(QtGui.QApplication.translate("DeviceTab", "Set User Tag 2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetUserTag2.setToolTip(QtGui.QApplication.translate("DeviceTab", "Set User Tag 2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditDeviceSettings.setText(QtGui.QApplication.translate("DeviceTab", "Edit Device Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDeviceInfo.setText(QtGui.QApplication.translate("DeviceTab", "Show Device Information", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareLatestStable.setText(QtGui.QApplication.translate("DeviceTab", "Latest Stable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareLatestStable.setToolTip(QtGui.QApplication.translate("DeviceTab", "Update Firmware From Latest Stable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPacketStats.setText(QtGui.QApplication.translate("DeviceTab", "Show Packet Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChangeActiveStreams.setText(QtGui.QApplication.translate("DeviceTab", "Change Active Streams", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRunTests.setText(QtGui.QApplication.translate("DeviceTab", "Run Hardware Tests", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetDeviceMode.setText(QtGui.QApplication.translate("DeviceTab", "Set Device Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareFromBranch.setText(QtGui.QApplication.translate("DeviceTab", "From Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareFromBranch.setToolTip(QtGui.QApplication.translate("DeviceTab", "Update Firmware From Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareFromCommit.setText(QtGui.QApplication.translate("DeviceTab", "From Specific Commit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareFromCommit.setToolTip(QtGui.QApplication.translate("DeviceTab", "Update Firmware From Specific Commit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareFromFile.setText(QtGui.QApplication.translate("DeviceTab", "From File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirmwareFromFile.setToolTip(QtGui.QApplication.translate("DeviceTab", "Update Firmware From File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForceRunBootloader.setText(QtGui.QApplication.translate("DeviceTab", "Force Run Bootloader", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForceRunApplication.setText(QtGui.QApplication.translate("DeviceTab", "Force Run Application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForceRunApplication.setToolTip(QtGui.QApplication.translate("DeviceTab", "Force Run Application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForceReset.setText(QtGui.QApplication.translate("DeviceTab", "Force Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForceReset.setToolTip(QtGui.QApplication.translate("DeviceTab", "Force Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRaiseException.setText(QtGui.QApplication.translate("DeviceTab", "Raise Exception", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRaiseException.setToolTip(QtGui.QApplication.translate("DeviceTab", "Raise Exception", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecoverNVM.setText(QtGui.QApplication.translate("DeviceTab", "Recover NVM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecoverNVM.setToolTip(QtGui.QApplication.translate("DeviceTab", "Recover NVM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalibrate.setText(QtGui.QApplication.translate("DeviceTab", "Start Calibration", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import GraphicsLayoutWidget
