---

- name: Install required packages
  package:
    name: '{{ q("flattened", (resolvconf__base_packages
                              + resolvconf__packages)) }}'
    state: 'present'
  register: resolvconf__register_packages
  until: resolvconf__register_packages is succeeded
  when: resolvconf__enabled|bool

- name: Divert original interface-order file
  command: dpkg-divert --quiet --local
                       --divert '/etc/resolvconf/interface-order.dpkg-divert'
                       --rename '/etc/resolvconf/interface-order'
  args:
    creates: '/etc/resolvconf/interface-order.dpkg-divert'
  register: resolvconf__register_interface_order_divert
  when: resolvconf__enabled|bool and resolvconf__deploy_state == 'present'

- name: Generate /etc/resolvconf/interface-order configuration
  template:
    src: 'etc/resolvconf/interface-order.j2'
    dest: '/etc/resolvconf/interface-order'
    mode: '0644'
  register: resolvconf__register_interface_order_config
  when: resolvconf__enabled|bool and resolvconf__deploy_state == 'present'

- name: Revert the original interface-order configuration
  shell: rm -f /etc/resolvconf/interface-order
         ; dpkg-divert --quiet --local --rename \
                       --remove /etc/resolvconf/interface-order
  args:
    removes: '/etc/resolvconf/interface-order.dpkg-divert'
    warn: False
  register: resolvconf__register_interface_order_revert
  when: resolvconf__enabled|bool and resolvconf__deploy_state == 'absent'

- name: Regenerate /etc/resolv.conf
  command: resolvconf -u
  when: (resolvconf__enabled|bool and
         (resolvconf__register_interface_order_divert is changed or
          resolvconf__register_interface_order_config is changed or
          resolvconf__register_interface_order_revert is changed))

- name: Make sure Ansible fact directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    mode: '0755'

- name: Generate resolvconf Ansible local facts
  template:
    src: 'etc/ansible/facts.d/resolvconf.fact.j2'
    dest: '/etc/ansible/facts.d/resolvconf.fact'
    mode: '0755'
  register: resolvconf__register_facts

- name: Reload facts if they were modified
  action: setup
  when: resolvconf__register_facts is changed
