language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"  # 3.4 & 2.7 only test flit_core - see tox.ini
  - "2.7"

install:
  - pip install tox-travis codecov
script: tox
after_success: codecov
