
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-17T16:59:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "19c3698ac32200cf23b4f882ffb5fd1b1eb5b3df",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
