
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T10:57:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c18f2f2da857301d96f1b88a4483c53cefb69188",
 "version": "0.72.0.dev"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
