[tool.poetry]
name = "demo-project"
version = "0.1.0"
description = ""
authors = ["Daniel Eitan <daniel.eitan@whitesourcesoftware.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pendulum = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
