package:
  name: discon
  version: "2.7.1"

source:
# this is used for build from git hub
  git_rev: 2.7.1
  git_url: https://github.com/mjirik/discon.git

# this is used for pypi 
  # fn: io3d-2.7.10.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-2.7.10.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
   entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    - discon = discon:main
    #
    # Would create an entry point called io3d that calls io3d.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - conda-build
    - anaconda-client
    - gitpython
    - bumpversion
    - click
    - loguru

  run:
    - python
    - setuptools
    - conda-build
    - anaconda-client
    - gitpython
    - bumpversion
    - click
    - loguru

test:
  # Python imports
  imports:
    - discon

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/disco
  license: BSD License
  summary: 'distribution to pypi and conda'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
