
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-27T19:26:52-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a6d7a38740fe55c64b8a94dc643accacbe1c941",
 "version": "0.2.6rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
