# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-18 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bee_django_course_simple', '0004_auto_20190417_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course/%Y/%m/%d', verbose_name='\u56fe\u7247')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_user_image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bee_django_course_simple_user_image',
            },
        ),
    ]
