# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-21 10:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_course_simple', '0010_question_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='section', chained_model_field='section', null=True, on_delete=django.db.models.deletion.CASCADE, to='bee_django_course_simple.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
