# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-06 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_course_simple', '0027_auto_20190601_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
