[tool.poetry]
name = "python-configuration"
version = "0.4.1"
description = "A library to load configuration parameters from multiple sources and formats"
authors = [
    "Tiago Requeijo <tiago.requeijo.dev@gmail.com>"
]
readme = 'README.md'
license = "MIT"
repository = "https://github.com/tr11/python-configuration"
homepage = "https://github.com/tr11/python-configuration"
keywords = ['configuration', 'settings', 'json', 'yaml', 'toml', 'ini']
packages = [
    { include = "config" },
]
include = ["config/py.typed"]

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = {version = "^5.1", optional = true}
toml = {version = "^0.10.0",optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-cov = "^2.6"
pytest-flake8 = "^1.0"
mypy = "^0.730"
pytest-mypy = "^0.4.1"
flake8-docstrings = "^1.3"
flake8-comprehensions = "^2.0"
flake8-import-order = "^0.18.0"
flake8-bugbear = "^19.0"
flake8-blind-except = "^0.1.1"
flake8-builtins = "^1.4"
sphinx = "^2.1"
sphinx-autodoc-typehints = "^1.6"
pydocstyle = "^4.0"
pytest-black = "^0.3.7"

[tool.poetry.extras]
yaml = ["pyyaml"]
toml = ["toml"]

[build-system]
requires = ["poetry>=1.0.0b1"]
build-backend = "poetry.masonry.api"
