
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-28T20:39:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c158208688e64997f2bde4554ec683d946e66cb",
 "version": "0.10.13.post.dev52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
