
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-28T06:25:15-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac380f5013ccfd8f4329f9b3fe49d50a8a44f5e3",
 "version": "0.8.1.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
