dist: xenial
language: python
cache: pip

env:
  global:
    TOXENV: python

matrix:
  fast_finish: true

  include:
    - python: 3.7
      name: Linting code smells
      env:
        TOXENV: lint-code-style
    - python: 3.7
      name: Linting type matching
      env:
        TOXENV: lint-mypy
    - python: 3.7
      name: Making sure that docs build is healthy
      env:
        TOXENV: docs
    - python: &latest_py3 3.8
    - python: 3.7
    - python: 3.6

    - stage: deploy
      if: tag IS present
      python: *latest_py3
      env:
        TOXENV: release
      after_script: skip

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - codecov --env TRAVIS_OS_NAME,TOXENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
