
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-18T09:54:18-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "52b53b3f609f147e4c8a9b8965ebad8b075e0b4b",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
