version: 2

jobs:
  build:
    docker:
      - image: bpiwowar/experimaestro-test-main
      - image: bpiwowar/experimaestro-test-remote
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: Creating Build Files
          command: |
            cmake -GNinja -H. -Bbuild
      - run:
          name: Building
          command: |
            ninja -j 2 -C build experimaestro-tests
      - run:
          name: Test
          command: |
            # Protect the directory so that ssh does not complain
            chmod og-rwx docker/remote/userdir/.ssh
            # TODO: include SSH tests on circle-ci
            GTEST_FILTER="-SshTest:*" CTEST_OUTPUT_ON_FAILURE=1 ninja -C build test