[tool.poetry]
name = "mailables"
version = "0.0.2"
description = "A developer-centric utility for sending asynchronous mails."
authors = ["Alex Oleshkevich <alex.oleshkevich@gmail.com>"]
readme = './README.md'
homepage = 'https://github.com/alex-oleshkevich/mailables'
repository = 'https://github.com/alex-oleshkevich/mailables.git'
keywords = ['asyncio', 'email', 'mailer', 'mail']
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
aiofiles = {version = "^0.4.0", optional = true}
aiosmtplib = {version = "^1.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-asyncio = "^0.10.0"
aiosmtpd = "^1.2"
coverage = "^4.5"
pytest-sugar = "^0.9.2"
pytest-cov = "^2.8"
mypy = "^0.740.0"

[tool.poetry.extras]
aiofiles = ["aiofiles"]
aiosmtplib = ["aiosmtplib"]
full = ["aiosmtplib", "aiofiles"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
