[tool.poetry]
name = "aio_pika_rpc"
version = "1.2.0"
description = "aio-pika RPC"
authors = ["m.shlyamov <m.shlyamov@yandex.com>"]
homepage = "https://github.com/SandLabs/aio-pika-rpc"
license = "MIT"
readme = "README.md"
classifiers = [
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Internet',
    'Topic :: Software Development',
    'Topic :: Software Development :: Libraries',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]

[tool.poetry.dependencies]
python = "^3.6"
aio-pika = ">=6.3"
ddtrace = ">=0.30"
msgpack = ">=0.6"

[tool.poetry.dev-dependencies]
prospector = ">=1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
