# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2019-11-22 19:45:41 UTC
from __future__ import unicode_literals
import datetime

version = "3.0.2"
githash = "54a145a40050e3ed193a73f364d9f59e08ffd6d2"


major = 3
minor = 0
bugfix = 2

release = True
timestamp = datetime.datetime(2019, 11, 22, 19, 45, 41)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
