[tool.poetry]
name = "keybasepy"
version = "0.1.2"
description = "A bot library for keybase"
authors = ["dnorhoj"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pykeybasebot = "^0.1.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
