non_countries = [
    'ARB',
    'CSS',
    'CEB',
    'EAR',
    'EAS',
    'EAP',
    'TEA',
    'EMU',
    'ECS',
    'ECA',
    'TEC',
    'EUU',
    'FCS',
    'HPC',
    'IBD',
    'IBT',
    'IDB',
    'IDX',
    'IDA',
    'LTE',
    'LCN',
    'LAC',
    'TLA',
    'LDC',
    'LMY',
    'MEA',
    'MNA',
    'TMN',
    'MIC',
    'NAC',
    'OED',
    'OSS',
    'PSS',
    'PST',
    'PRE',
    'SST',
    'SAS',
    'TSA',
    'SSF',
    'SSA',
    'TSS',
    'WLD']

sources = {'DBS': {'id': '1', 'name': 'Doing Business'},
           'WDI': {'id': '2', 'name': 'World Development Indicators'},
           'WGI': {'id': '3', 'name': 'Worldwide Governance Indicators'},
           'SNM': {'id': '5', 'name': 'Subnational Malnutrition Database'},
           'IDS': {'id': '6', 'name': 'International Debt Statistics'},
           'ADI': {'id': '11', 'name': 'Africa Development Indicators'},
           'EDS': {'id': '12', 'name': 'Education Statistics'},
           'ESY': {'id': '13', 'name': 'Enterprise Surveys'},
           'GDS': {'id': '14', 'name': 'Gender Statistics'},
           'GEM': {'id': '15', 'name': 'Global Economic Monitor'},
           'HNP': {'id': '16', 'name': 'Health Nutrition and Population Statistics'},
           'IDA': {'id': '18', 'name': 'IDA Results Measurement System'},
           'MDG': {'id': '19', 'name': 'Millennium Development Goals'},
           'PSD': {'id': '20', 'name': 'Quarterly Public Sector Debt'},
           'QDS': {'id': '22', 'name': 'Quarterly External Debt Statistics SDDS'},
           'QDG': {'id': '23', 'name': 'Quarterly External Debt Statistics GDDS'},
           'POV': {'id': '24', 'name': 'Poverty and Equity'},
           'JOB': {'id': '25', 'name': 'Jobs'},
           'GEP': {'id': '27', 'name': 'Global Economic Prospects'},
           'FDX': {'id': '28', 'name': 'Global Financial Inclusion'},
           'GSP': {'id': '29',
                   'name': 'The Atlas of Social Protection: Indicators of Resilience and Equity'},
           'ED1': {'id': '30',
                   'name': 'Exporter Dynamics Database – Indicators at Country-Year Level'},
           'CPI': {'id': '31', 'name': 'Country Policy and Institutional Assessment'},
           'GFD': {'id': '32', 'name': 'Global Financial Development'},
           'G2F': {'id': '33', 'name': 'G20 Financial Inclusion Indicators'},
           'GPE': {'id': '34', 'name': 'Global Partnership for Education'},
           'SE4': {'id': '35', 'name': 'Sustainable Energy for All'},
           'BBS': {'id': '36', 'name': 'Statistical Capacity Indicators'},
           'LEL': {'id': '37', 'name': 'LAC Equity Lab'},
           'SNP': {'id': '38', 'name': 'Subnational Poverty'},
           'HNQ': {'id': '39',
                   'name': 'Health Nutrition and Population Statistics by Wealth Quintile'},
           'HPP': {'id': '40', 'name': 'Population estimates and projections'},
           'CPS': {'id': '41',
                   'name': 'Country Partnership Strategy for India (FY2013 - 17)'},
           'WAT': {'id': '43', 'name': 'Adjusted Net Savings'},
           'RIS': {'id': '44', 'name': 'Readiness for Investment in Sustainable Energy'},
           'IDD': {'id': '45',
                   'name': 'Indonesia Database for Policy and Economic Research'},
           'SDG': {'id': '46', 'name': 'Sustainable Development Goals '},
           'SNT': {'id': '50', 'name': 'Subnational Population'},
           'JED': {'id': '54', 'name': 'Joint External Debt Hub'},
           'WDA': {'id': '57', 'name': 'WDI Database Archives'},
           'UHC': {'id': '58', 'name': 'Universal Health Coverage'},
           'WAC': {'id': '59', 'name': 'Wealth Accounts'},
           'EFT': {'id': '60', 'name': 'Economic Fitness'},
           'PRQ': {'id': '61', 'name': 'PPPs Regulatory Quality'},
           'ICP': {'id': '62', 'name': 'International Comparison Program (ICP) 2011'},
           'HCI': {'id': '63', 'name': 'Human Capital Index'},
           'WBI': {'id': '64', 'name': 'Worldwide Bureaucracy Indicators'},
           'HPI': {'id': '65',
                   'name': 'Health Equity and Financial Protection Indicators'},
           'LPI': {'id': '66', 'name': 'Logistics Performance Index'},
           'PF1': {'id': '67', 'name': 'PEFA 2011'},
           'PF6': {'id': '68', 'name': 'PEFA 2016'},
           'RFA': {'id': '69',
                   'name': 'Global Financial Inclusion and Consumer Protection Survey'},
           'EF2': {'id': '70', 'name': 'Economic Fitness 2'},
           'IC5': {'id': '71', 'name': 'International Comparison Program (ICP) 2005'},
           'PFT': {'id': '72', 'name': 'PEFA_Test'},
           'RFI': {'id': '73',
                   'name': 'Global Financial Inclusion and Consumer Protection Survey (Internal)'},
           'ESG': {'id': '75', 'name': 'Environment, Social and Governance (ESG) Data'}}
