# Generated by Django 2.2.2 on 2019-06-30 07:03

from django.db import migrations, models
import djangopost.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=djangopost.models.image_upload_destination),
        ),
    ]
