[tool.poetry]
name = "flubber"
version = "0.0.1a0"
description = ""
authors = ["Dharwin Perez <dhararon@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
structlog = "^19.2"
flask = "^1.1"
werkzeug = "^0.16.0"
gunicorn = "^20.0"
flask_talisman = "^0.7.0"
flask_restful = "^0.3.7"
Flask-Opentracing = "^1.1"
flask-sqlalchemy = "^2.4"
marshmallow-sqlalchemy = "^0.19.0"
omegaconf = "^1.4"
factory_boy = "^2.12"
pre-commit = "^1.20"
cleo = "^0.7.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flask_profiler = "^1.8"
flask-debugtoolbar = "^0.10.1"
pytest-flask = "^0.15.0"
nplusone = "^1.0"

[tool.poetry.scripts]
flubber = "flubber.console:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
