
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-20T14:58:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "17e2d936bf7b88ef4bc6d5d87c7693e0faa6663e",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
