
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-18T16:07:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9851198f9e64ccb941b114d7942da864bd3f2b92",
 "version": "0.9.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
