dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: f3THVFaLhKUStaYcrl2KQxXf/60ucgQ/UmK5jmKtRqjduWc1hHBi3hepyOAwqvcSW1TLD0rBxW6Y+Ny1dgv0XMv3kVzfa6u/7YCvRC1jaHiJrLqNu//HiX3ExM3phiptnH9yYD4dp3QvaVviB6Fxal3iLs4NwHhpHis/7Ky3QpywX7CPxOka9U4pSjsNLtSZbPDdZKJnHzAyk9crG+NxHWeuWQB/3tUFKOT5AfYY4aJ+uzmFxK7ykleAZsOG1Kmt770Pua8zqN5O2DcbVOScQ32eviLJJSPzEHSOmtQkqE5BjImPXmWEMzcHgSmOuwL5rTfWAVAiIbJY5eYtT6CJAV2ttRMuDJnTaZ/mnOCWHDJqDVNgWihxyYvaN/Sra/nkURziW8+ROOR9pSfL0CZOdEFWUoHMuKiJ/RFF4W0pXji9y4tqYm5xUUSkEfb6MTPtYu16mm+nPSsX2jJOryVdGhWZo3JYgj4AK61G91ilHtfhbLveWWZvg8S+oKrf2xddHBfE8XxyGhM1108AGximwXMM8lEqEKYE7gV7hIP5hLTE4iwW4Ckbib7ERS9X0Z1o7uenHb54Q+gb3kTcSPtEdSyeJgMqTI+Hq0rz5VO8dd0QQX6ybCQxcHOF9yPPVca4ekaTwiY+vxV+s31E8sKJVhETD91TVqvT7PGq2oKEHyI=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_sdcard.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-sd --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
