# Generated by Django 2.2.6 on 2019-11-08 05:52

from django.db import migrations, models
import django.db.models.deletion
import django_crypto_fields.fields.encrypted_char_field


class Migration(migrations.Migration):

    dependencies = [
        ("ambition_rando", "0006_auto_20191007_0556"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="randomizationlist",
            options={
                "ordering": ("site_name", "sid"),
                "permissions": (("display_assignment", "Can display assignment"),),
            },
        ),
        migrations.AlterField(
            model_name="historicalrandomizationlist",
            name="allocation",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text=" (Encryption: RSA local)",
                max_length=71,
                null=True,
                verbose_name="Original integer allocation",
            ),
        ),
        migrations.AlterField(
            model_name="randomizationlist",
            name="allocated_site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.Site",
            ),
        ),
        migrations.AlterField(
            model_name="randomizationlist",
            name="allocation",
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                blank=True,
                help_text=" (Encryption: RSA local)",
                max_length=71,
                null=True,
                verbose_name="Original integer allocation",
            ),
        ),
    ]
