[tool.poetry]
name = "instaffo-scikit-learn"
version = "0.2.1"
description = "This project contains custom scikit-learn estimators that we use."
license = "MIT"
authors = ["Instaffo GmbH <info@instaffo.de>", "Jan-Benedikt Jagusch <jan@instaffo.de>"]
readme = "README.md"
repository = "https://gitlab.com/InstaffoOpenSource/DataScience/instaffo-scikit-learn"
homepage = "https://instaffo.com"
keywords = ["scikit-learn", "instaffo"]
packages = [
	{include = "instaffo_sklearn"}
]

[tool.poetry.dependencies]
joblib = "^0.13"
numpy = "^1.16"
pandas = "^0.25"
python = "^3.6"
scikit-learn = "^0.21"
scipy = "^1.3"

[tool.poetry.dev-dependencies]
black = {version = "==19.3b0", allows-prereleases = true}
ipykernel = "^5.1"
joblib = "^0.13"
matplotlib = "^3.0"
pylint = "^2.3"
pytest = "^4.6"
tox = "^3.12"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
