[tool.poetry]
name = "colourize"
version = "0.1.0"
description = "Convert image datasets to other colourspaces."
authors = ["Derek Goddeau <derek.j.goddeau@pm.me>"]
license = "Apache-2.0"
keywords = ['computer vision',
            'augmentation',
            'image',
            'color',
            'colour']
readme = "README.md"
repository = "https://gitlab.com/starshell/datadyne/colourize"
homepage = "https://gitlab.com/starshell/datadyne/colourize"

[tool.poetry.dependencies]
python = "^3.6"
colour-science = "0.3.14"
tqdm = "^4.39"
torch = "^1.2.0"
pyyaml = "^5.1"
torchvision = "^0.4.2"
scikit-image = "^0.16.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
clz = 'colourize.colourize:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

