version: "2"

services:
  gate:
    build: .
    # depends_on:
    #   - "postgres"
    #   - "oarnode1"
    networks:
      - "back"
    ports:
      - "2200:22"
    entrypoint: /root/run.sh
    volumes:
       - ./userdir:/home/testuser
    restart: always

  # oarnode1:
  #   build: .
  #   networks:
  #     - "back"
  #   entrypoint: /root/start-oar-node.sh
  #   restart: always
  #   volumes:
  #      - ./userdir:/home/testuser

  # mysql:
  #   image: "mariadb:10.3"
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_ROOT_PASSWORD: ""
  #   restart: always
  #   networks:
  #     - "back"

  # postgres: 
  #   image: "postgres"
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   networks:
  #     - "back"


  # proxy:
  #   image: "jwilder/nginx-proxy:alpine"
  #   ports:
  #     - "80:80"
  #   networks:
  #     front:
  #       aliases:
  #         - "${DOCKER_DEV_DOMAIN}"
  #   volumes:
  #     - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
  back: {}

# volumes:
#   userdir: {}