# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration_channel.ui'
#
# Created: Thu Oct 24 14:18:03 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CalibrationChannel(object):
    def setupUi(self, CalibrationChannel):
        CalibrationChannel.setObjectName("CalibrationChannel")
        CalibrationChannel.resize(195, 254)
        self.verticalLayout = QtGui.QVBoxLayout(CalibrationChannel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calibrationEnabled = QtGui.QCheckBox(CalibrationChannel)
        self.calibrationEnabled.setChecked(True)
        self.calibrationEnabled.setObjectName("calibrationEnabled")
        self.verticalLayout.addWidget(self.calibrationEnabled)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.unitLabel = QtGui.QLabel(CalibrationChannel)
        self.unitLabel.setObjectName("unitLabel")
        self.horizontalLayout_3.addWidget(self.unitLabel)
        self.unit = QtGui.QLabel(CalibrationChannel)
        self.unit.setObjectName("unit")
        self.horizontalLayout_3.addWidget(self.unit)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.selectUnit = QtGui.QPushButton(CalibrationChannel)
        self.selectUnit.setObjectName("selectUnit")
        self.horizontalLayout_3.addWidget(self.selectUnit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.acRadioButton = QtGui.QRadioButton(CalibrationChannel)
        self.acRadioButton.setChecked(True)
        self.acRadioButton.setObjectName("acRadioButton")
        self.horizontalLayout_2.addWidget(self.acRadioButton)
        self.linearRadioButton = QtGui.QRadioButton(CalibrationChannel)
        self.linearRadioButton.setObjectName("linearRadioButton")
        self.horizontalLayout_2.addWidget(self.linearRadioButton)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(CalibrationChannel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.linearPage = QtGui.QWidget()
        self.linearPage.setObjectName("linearPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.linearPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.linearCapture = QtGui.QPushButton(self.linearPage)
        self.linearCapture.setObjectName("linearCapture")
        self.horizontalLayout_5.addWidget(self.linearCapture)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.plotButton = QtGui.QPushButton(self.linearPage)
        self.plotButton.setEnabled(False)
        self.plotButton.setObjectName("plotButton")
        self.horizontalLayout_5.addWidget(self.plotButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.linearTable = QtGui.QTableWidget(self.linearPage)
        self.linearTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.linearTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.linearTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.linearTable.setObjectName("linearTable")
        self.linearTable.setColumnCount(3)
        self.linearTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.linearTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.linearTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.linearTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.linearTable)
        self.stackedWidget.addWidget(self.linearPage)
        self.acPage = QtGui.QWidget()
        self.acPage.setObjectName("acPage")
        self.formLayout = QtGui.QFormLayout(self.acPage)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.capturedMagnitudeLabel = QtGui.QLabel(self.acPage)
        self.capturedMagnitudeLabel.setObjectName("capturedMagnitudeLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.capturedMagnitudeLabel)
        self.capturedOffsetLabel = QtGui.QLabel(self.acPage)
        self.capturedOffsetLabel.setObjectName("capturedOffsetLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.capturedOffsetLabel)
        self.actualMagnitudeLabel = QtGui.QLabel(self.acPage)
        self.actualMagnitudeLabel.setObjectName("actualMagnitudeLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.actualMagnitudeLabel)
        self.actualOffsetLabel = QtGui.QLabel(self.acPage)
        self.actualOffsetLabel.setObjectName("actualOffsetLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.actualOffsetLabel)
        self.capturedMagnitude = UnitFormatterDoubleSpinBox(self.acPage)
        self.capturedMagnitude.setObjectName("capturedMagnitude")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.capturedMagnitude)
        self.actualMagnitude = UnitFormatterDoubleSpinBox(self.acPage)
        self.actualMagnitude.setObjectName("actualMagnitude")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.actualMagnitude)
        self.capturedOffset = UnitFormatterDoubleSpinBox(self.acPage)
        self.capturedOffset.setObjectName("capturedOffset")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.capturedOffset)
        self.actualOffset = UnitFormatterDoubleSpinBox(self.acPage)
        self.actualOffset.setObjectName("actualOffset")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.actualOffset)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.acCapture = QtGui.QPushButton(self.acPage)
        self.acCapture.setObjectName("acCapture")
        self.horizontalLayout_4.addWidget(self.acCapture)
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.acPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scaleLabel = QtGui.QLabel(CalibrationChannel)
        self.scaleLabel.setObjectName("scaleLabel")
        self.horizontalLayout.addWidget(self.scaleLabel)
        self.scale = QtGui.QLineEdit(CalibrationChannel)
        self.scale.setReadOnly(True)
        self.scale.setObjectName("scale")
        self.horizontalLayout.addWidget(self.scale)
        self.offsetLabel = QtGui.QLabel(CalibrationChannel)
        self.offsetLabel.setObjectName("offsetLabel")
        self.horizontalLayout.addWidget(self.offsetLabel)
        self.offset = QtGui.QLineEdit(CalibrationChannel)
        self.offset.setReadOnly(True)
        self.offset.setObjectName("offset")
        self.horizontalLayout.addWidget(self.offset)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CalibrationChannel)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CalibrationChannel)
        CalibrationChannel.setTabOrder(self.calibrationEnabled, self.selectUnit)
        CalibrationChannel.setTabOrder(self.selectUnit, self.acRadioButton)
        CalibrationChannel.setTabOrder(self.acRadioButton, self.linearRadioButton)
        CalibrationChannel.setTabOrder(self.linearRadioButton, self.acCapture)
        CalibrationChannel.setTabOrder(self.acCapture, self.capturedMagnitude)
        CalibrationChannel.setTabOrder(self.capturedMagnitude, self.capturedOffset)
        CalibrationChannel.setTabOrder(self.capturedOffset, self.actualMagnitude)
        CalibrationChannel.setTabOrder(self.actualMagnitude, self.actualOffset)
        CalibrationChannel.setTabOrder(self.actualOffset, self.linearCapture)
        CalibrationChannel.setTabOrder(self.linearCapture, self.linearTable)
        CalibrationChannel.setTabOrder(self.linearTable, self.scale)
        CalibrationChannel.setTabOrder(self.scale, self.offset)

    def retranslateUi(self, CalibrationChannel):
        self.calibrationEnabled.setText(QtGui.QApplication.translate("CalibrationChannel", "Calibrate channel", None, QtGui.QApplication.UnicodeUTF8))
        self.unitLabel.setText(QtGui.QApplication.translate("CalibrationChannel", "Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.unit.setText(QtGui.QApplication.translate("CalibrationChannel", "Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.selectUnit.setText(QtGui.QApplication.translate("CalibrationChannel", "Select Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.acRadioButton.setText(QtGui.QApplication.translate("CalibrationChannel", "AC RMS", None, QtGui.QApplication.UnicodeUTF8))
        self.linearRadioButton.setText(QtGui.QApplication.translate("CalibrationChannel", "1st Order Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.linearCapture.setText(QtGui.QApplication.translate("CalibrationChannel", "Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.plotButton.setText(QtGui.QApplication.translate("CalibrationChannel", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.linearTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("CalibrationChannel", "Captured", None, QtGui.QApplication.UnicodeUTF8))
        self.linearTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("CalibrationChannel", "Actual", None, QtGui.QApplication.UnicodeUTF8))
        self.linearTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("CalibrationChannel", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.capturedMagnitudeLabel.setText(QtGui.QApplication.translate("CalibrationChannel", "Captured RMS Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.capturedOffsetLabel.setText(QtGui.QApplication.translate("CalibrationChannel", "Captured DC Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.actualMagnitudeLabel.setText(QtGui.QApplication.translate("CalibrationChannel", "Actual RMS Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.actualOffsetLabel.setText(QtGui.QApplication.translate("CalibrationChannel", "Actual DC Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.acCapture.setText(QtGui.QApplication.translate("CalibrationChannel", "Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setText(QtGui.QApplication.translate("CalibrationChannel", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetLabel.setText(QtGui.QApplication.translate("CalibrationChannel", "Offset", None, QtGui.QApplication.UnicodeUTF8))

from acheron.unit_formatter_spinbox import UnitFormatterDoubleSpinBox
