# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotmain.ui'
#
# Created: Tue May  7 17:09:59 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PlotMainWindow(object):
    def setupUi(self, PlotMainWindow):
        PlotMainWindow.setObjectName("PlotMainWindow")
        PlotMainWindow.resize(1200, 800)
        self.centralwidget = QtGui.QWidget(PlotMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(2, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(3, -1, 3, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.warningLabel = QtGui.QLabel(self.centralwidget)
        self.warningLabel.setStyleSheet("QLabel { color : red ; font-weight : bold ; font-size : 18px ; }")
        self.warningLabel.setObjectName("warningLabel")
        self.horizontalLayout_2.addWidget(self.warningLabel)
        self.uploadRateLabel = QtGui.QLabel(self.centralwidget)
        self.uploadRateLabel.setMinimumSize(QtCore.QSize(75, 25))
        self.uploadRateLabel.setObjectName("uploadRateLabel")
        self.horizontalLayout_2.addWidget(self.uploadRateLabel)
        self.uploadProgress = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadProgress.sizePolicy().hasHeightForWidth())
        self.uploadProgress.setSizePolicy(sizePolicy)
        self.uploadProgress.setMinimumSize(QtCore.QSize(175, 25))
        self.uploadProgress.setMaximum(5957928)
        self.uploadProgress.setProperty("value", 2359296)
        self.uploadProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.uploadProgress.setObjectName("uploadProgress")
        self.horizontalLayout_2.addWidget(self.uploadProgress)
        self.uploadNameLabel = QtGui.QLabel(self.centralwidget)
        self.uploadNameLabel.setObjectName("uploadNameLabel")
        self.horizontalLayout_2.addWidget(self.uploadNameLabel)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.datetimeLabel = QtGui.QLabel(self.centralwidget)
        self.datetimeLabel.setObjectName("datetimeLabel")
        self.horizontalLayout_2.addWidget(self.datetimeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        PlotMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PlotMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuStreaming = QtGui.QMenu(self.menubar)
        self.menuStreaming.setObjectName("menuStreaming")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuCheckForUpdates = QtGui.QMenu(self.menuHelp)
        self.menuCheckForUpdates.setObjectName("menuCheckForUpdates")
        self.menuDevices = QtGui.QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuMarkForUpload = QtGui.QMenu(self.menuTools)
        self.menuMarkForUpload.setObjectName("menuMarkForUpload")
        PlotMainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(PlotMainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        PlotMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRescanUSB = QtGui.QAction(PlotMainWindow)
        self.actionRescanUSB.setObjectName("actionRescanUSB")
        self.actionExit = QtGui.QAction(PlotMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPreferences = QtGui.QAction(PlotMainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtGui.QAction(PlotMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDisableStreaming = QtGui.QAction(PlotMainWindow)
        self.actionDisableStreaming.setCheckable(True)
        self.actionDisableStreaming.setObjectName("actionDisableStreaming")
        self.actionDisableArchiving = QtGui.QAction(PlotMainWindow)
        self.actionDisableArchiving.setCheckable(True)
        self.actionDisableArchiving.setObjectName("actionDisableArchiving")
        self.actionFindTCPDevices = QtGui.QAction(PlotMainWindow)
        self.actionFindTCPDevices.setObjectName("actionFindTCPDevices")
        self.actionEnableRFPower = QtGui.QAction(PlotMainWindow)
        self.actionEnableRFPower.setObjectName("actionEnableRFPower")
        self.actionDisableRFPower = QtGui.QAction(PlotMainWindow)
        self.actionDisableRFPower.setObjectName("actionDisableRFPower")
        self.actionPause = QtGui.QAction(PlotMainWindow)
        self.actionPause.setCheckable(True)
        self.actionPause.setObjectName("actionPause")
        self.actionResume = QtGui.QAction(PlotMainWindow)
        self.actionResume.setCheckable(True)
        self.actionResume.setObjectName("actionResume")
        self.actionClosableTabs = QtGui.QAction(PlotMainWindow)
        self.actionClosableTabs.setCheckable(True)
        self.actionClosableTabs.setObjectName("actionClosableTabs")
        self.actionUpdateLatestStable = QtGui.QAction(PlotMainWindow)
        self.actionUpdateLatestStable.setObjectName("actionUpdateLatestStable")
        self.actionUpdateSpecificBranch = QtGui.QAction(PlotMainWindow)
        self.actionUpdateSpecificBranch.setObjectName("actionUpdateSpecificBranch")
        self.actionUpdateSpecificCommit = QtGui.QAction(PlotMainWindow)
        self.actionUpdateSpecificCommit.setObjectName("actionUpdateSpecificCommit")
        self.actionUpdateCurrentBranch = QtGui.QAction(PlotMainWindow)
        self.actionUpdateCurrentBranch.setObjectName("actionUpdateCurrentBranch")
        self.actionDownloadFirmware = QtGui.QAction(PlotMainWindow)
        self.actionDownloadFirmware.setObjectName("actionDownloadFirmware")
        self.actionMarkFiles = QtGui.QAction(PlotMainWindow)
        self.actionMarkFiles.setObjectName("actionMarkFiles")
        self.actionMarkDirectory = QtGui.QAction(PlotMainWindow)
        self.actionMarkDirectory.setObjectName("actionMarkDirectory")
        self.menuFile.addAction(self.actionExit)
        self.menuStreaming.addAction(self.actionDisableStreaming)
        self.menuStreaming.addAction(self.actionDisableArchiving)
        self.menuSettings.addAction(self.actionClosableTabs)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuCheckForUpdates.addAction(self.actionUpdateLatestStable)
        self.menuCheckForUpdates.addAction(self.actionUpdateCurrentBranch)
        self.menuCheckForUpdates.addAction(self.actionUpdateSpecificBranch)
        self.menuCheckForUpdates.addAction(self.actionUpdateSpecificCommit)
        self.menuHelp.addAction(self.menuCheckForUpdates.menuAction())
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuDevices.addAction(self.actionRescanUSB)
        self.menuDevices.addAction(self.actionFindTCPDevices)
        self.menuMarkForUpload.addAction(self.actionMarkFiles)
        self.menuMarkForUpload.addAction(self.actionMarkDirectory)
        self.menuTools.addAction(self.actionDownloadFirmware)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuMarkForUpload.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevices.menuAction())
        self.menubar.addAction(self.menuStreaming.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionEnableRFPower)
        self.toolBar.addAction(self.actionDisableRFPower)
        self.toolBar.addAction(self.actionRescanUSB)
        self.toolBar.addAction(self.actionFindTCPDevices)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionResume)

        self.retranslateUi(PlotMainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), PlotMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(PlotMainWindow)

    def retranslateUi(self, PlotMainWindow):
        PlotMainWindow.setWindowTitle(QtGui.QApplication.translate("PlotMainWindow", "Acheron", None, QtGui.QApplication.UnicodeUTF8))
        self.warningLabel.setText(QtGui.QApplication.translate("PlotMainWindow", "Warning: Archiving Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadRateLabel.setText(QtGui.QApplication.translate("PlotMainWindow", "350 kB/s", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadProgress.setFormat(QtGui.QApplication.translate("PlotMainWindow", "%v/%m (%p%)", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadNameLabel.setText(QtGui.QApplication.translate("PlotMainWindow", "20181029T2241Z_HSS2143.apd", None, QtGui.QApplication.UnicodeUTF8))
        self.datetimeLabel.setText(QtGui.QApplication.translate("PlotMainWindow", "0000-00-00T00:00:00Z", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("PlotMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStreaming.setTitle(QtGui.QApplication.translate("PlotMainWindow", "Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("PlotMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("PlotMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCheckForUpdates.setTitle(QtGui.QApplication.translate("PlotMainWindow", "Check for Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDevices.setTitle(QtGui.QApplication.translate("PlotMainWindow", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("PlotMainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMarkForUpload.setTitle(QtGui.QApplication.translate("PlotMainWindow", "Mark for Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRescanUSB.setText(QtGui.QApplication.translate("PlotMainWindow", "Rescan USB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("PlotMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("PlotMainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("PlotMainWindow", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisableStreaming.setText(QtGui.QApplication.translate("PlotMainWindow", "Disable Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisableArchiving.setText(QtGui.QApplication.translate("PlotMainWindow", "Disable Archiving", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFindTCPDevices.setText(QtGui.QApplication.translate("PlotMainWindow", "Find TCP Devices...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnableRFPower.setText(QtGui.QApplication.translate("PlotMainWindow", "Enable RF Power (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisableRFPower.setText(QtGui.QApplication.translate("PlotMainWindow", "Disable RF Power (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("PlotMainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResume.setText(QtGui.QApplication.translate("PlotMainWindow", "Resume", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClosableTabs.setText(QtGui.QApplication.translate("PlotMainWindow", "Easy Close Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClosableTabs.setToolTip(QtGui.QApplication.translate("PlotMainWindow", "Easy Close Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateLatestStable.setText(QtGui.QApplication.translate("PlotMainWindow", "Latest Stable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSpecificBranch.setText(QtGui.QApplication.translate("PlotMainWindow", "Specific Branch...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSpecificCommit.setText(QtGui.QApplication.translate("PlotMainWindow", "Specific Commit..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateCurrentBranch.setText(QtGui.QApplication.translate("PlotMainWindow", "Latest branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownloadFirmware.setText(QtGui.QApplication.translate("PlotMainWindow", "Download Firmware...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownloadFirmware.setToolTip(QtGui.QApplication.translate("PlotMainWindow", "Download Firmware...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarkFiles.setText(QtGui.QApplication.translate("PlotMainWindow", "Mark Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarkFiles.setToolTip(QtGui.QApplication.translate("PlotMainWindow", "Mark Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarkDirectory.setText(QtGui.QApplication.translate("PlotMainWindow", "Mark Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarkDirectory.setToolTip(QtGui.QApplication.translate("PlotMainWindow", "Mark Directory", None, QtGui.QApplication.UnicodeUTF8))

