[tool.poetry]
name = "ipyannotator"
version = "0.1.0"
description = "ipython widgets for data annotation"
authors = ["Palaimon OSS  <oss@palaimon.io>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
