[tool.poetry]
name = "seedy-quay"
version = "0.1.0"
# description = "Python extensions for working with Amazon Web Services' Cloud Development Kit"
description = "Placeholder"
readme = "README.md"
authors = ["Gary Donovan <gary.donovan@oovvuu.com>"]
license = "LGPL-3.0"
packages = [
    { include="seedyquay", from="src" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
