
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-18T20:20:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d16ef9e7a2e11c83bb9da8232f99532017f8d409",
 "version": "0.10.13.post.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
