
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-23T08:36:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "93dd6a17136894f55675076488a17e4087cb8a7a",
 "version": "0.0.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
