[tool.poetry]
name = "plex-posters"
version = "0.1.4"
description = ""
authors = ["dtomlinson <dtomlinson@panaetius.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
praw = "^6.4"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.740.0"
pudb = "^2019.2"
sphinx = "^2.2"
sphinx_rtd_theme = "^0.4.3"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
