language: python
os:
- linux
python:
- 3.6
- 3.7
- 2.7

addons:
  apt:
    packages:
    - python-setuptools
    - pandoc

script:
- python setup.py flake8

install:
- pip -q install --upgrade setuptools setuptools_scm
- pip -q install matplotlib pytest flake8 --upgrade


deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PW
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.7"