[tool.poetry]
name = "exex-cli"
version = "0.1.1"
description = "Command-line interface for extracting data from Excel documents."
authors = ["Viktor Persson <viktor.persson@arcsin.se>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/vikpe/exex-cli"
repository = "https://github.com/vikpe/exex-cli"
keywords = ["cli", "excel", "extract", "parser", "tool"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Topic :: Office/Business :: Financial :: Spreadsheet",
    "Topic :: Utilities",
    "Operating System :: POSIX",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]

[tool.poetry.dependencies]
python = "^3.6"
cleo = "=0.6.8"
exex = "^0.1.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
tox = "^3.14"
pytest-cov = "^2.8"
pytest-sugar = "^0.9.2"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
tox-pyenv = "^1.1"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
