
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-22T22:46:55-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "507659d79434845e50d48c247ff42d5efd336686",
 "version": "2.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
