[tool.poetry]
name = "flake8-requests"
version = "0.2.0"
description = "r2c checks for requests"
authors = ["R2C <hello@returntocorp.com>"]
readme = "README.md"
homepage = "https://bento.dev"
classifiers=[
  "Programming Language :: Python :: 3",
  "License :: Other/Proprietary License",
  "Operating System :: OS Independent",
]
packages = [
  { include = "flake8_requests"},
]
exclude = ["tests/**"]

[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.7.9"
pytest = "^5.3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins]
[tool.poetry.plugins."flake8.extension"]
r2c-requests="flake8_requests.main:Flake8Requests"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
