[tool.poetry]
name = "scdlbot"
version = "0.9.27"
description = "Telegram Bot for downloading MP3 rips of tracks/sets from SoundCloud, Bandcamp, YouTube with tags and artwork"
license = "MIT"
authors = ["George Pchelkin <george@pchelk.in>"]
readme = "README.rst"
homepage = "https://github.com/gpchelkin/scdlbot"
repository = "https://github.com/gpchelkin/scdlbot"
documentation = "https://scdlbot.readthedocs.io"
keywords = ["scdlbot", "telegram", "bot", "soundcloud", "bandcamp", "youtube", "audio", "music", "download"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Internet",
    "Operating System :: OS Independent",
    "Natural Language :: English",
]
include = ["AUTHORS.rst", "CONTRIBUTING.rst", "HISTORY.rst", "LICENSE", "README.rst", "tests/*", "docs/*.rst", "docs/conf.py", "docs/Makefile", "docs/make.bat", "docs/*.jpg", "docs/*.png", "docs/*.gif", "scdlbot/texts/*"]

[tool.poetry.scripts]
scdlbot = "scdlbot.__main__:main"

[tool.poetry.dependencies]
python = "^3.5"
python-telegram-bot = "10.1.0"
python-telegram-handler = "2.2"
boltons = "19.3.0"
plumbum = "1.6.7"
#For build and publish:
scdl = "1.6.12"
#For testing:
#scdl = { git = "https://github.com/flyingrub/scdl.git" }
bandcamp-downloader = "0.0.8.post12"
youtube-dl = "2019.11.28"
pydub = "0.23.1"
mutagen = "1.43.0"
patool = "1.12"
pyshorteners = "0.6.1"
logentries = "0.17"
celery = "4.3.0"
#transliterate = "1.10.2"

[tool.poetry.dev-dependencies]
pip = "19.3.1"
wheel = "0.33.6"
watchdog = "0.9.0"
flake8 = "3.7.9"
tox = "3.14.1"
coverage = "4.5.4"
Sphinx = "2.2.1"
cryptography = "2.8"
PyYAML = "5.1.2"
pytest = "5.3.1"

[build-system]
requires = ["poetry>=1.0.0b8"]
build-backend = "poetry.masonry.api"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
