# Generated by Django 2.2 on 2019-11-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_system', '0002_auto_20191119_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutop',
            name='link_view_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
