language: python
python:
- 3.7
script:
- pip install yapf
- diffs=$(yapf -dr --style=yapf.ini ./thunderbolt)
- if [ -n "$diffs" ]; then exit 1; fi
- python setup.py install
- python -m unittest discover -s ./test/
deploy:
  on:
    tags: true
  provider: pypi
  user: vaaaaanquish
  password:
    secure: NGiH3nBcSJlylbHaVlA+dZIAwqSvLV7TX+T45PIk/qcPHOsB+DbTtQ2VzqNlCN6+he6Xn4+0ztiWtzSOKF53k47hJD2b3NWT5+sEs6njJhj/SppJw9DLwKCFgmbzk9rMG6VrYPQVkLEo8sWkE6Wts8YOQGmzABcxbmG4/h9RcMZstPfQr+ywTKQrbLZ0dNxb9v0crjAOzm/oglxOJLqKCS9UDBoR/2vNUIkKH1Tt6l4+5WwzpzUSvS/G5CkP8ePV6rGhifiF3zdFXo66xhclrQHvNyV1jB90hBVYDxKBWQ+z52/hHN9/HD6MNMGDqdSanay1hg/w8G4jEc/VlK2iAs4s5PlOVsp/Pq2VvUJ6VV5jQwx9yVO0mSWvP5jERN1WWbQqKT3NuUFNi4rt9MZhfjtvpJWWobS/5Ci69DAGKl+Nx7E++YfLLWjxew4LSkEImUFhhYUOVew2aXY4qTN2j80yJHVCYAcSMOFS18kb5BjDfFZav6c9MjOpuZjvyh68RTr+FU5SnjV4GuBE81bXJKhWHMfgrWtR1wDsDNYWKvCNH6LBu65rLrWPAwx01VPLSBP/ZVPFQVgJEqcKi9Y2ag7ErjXkEmlseuReLGvLE62pRntv01dsAd4jYClY3sgXBm0Qa9X1LzrF4ofG9xMjwvUllkrF0sS1tocgRqBfp9U=
