
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-19T14:38:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee2092ffea7e91203c21aee0aa14ab47abb5b477",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
