[tool.poetry]
name = "django-command-log"
version = "0.2"
description = "Django management command auditing app"
authors = ["YunoJuno <code@yunojuno.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/yunojuno/django-managment-command-log"
repository = "https://github.com/yunojuno/django-managment-command-log"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
]
packages = [
    { include = "command_log" }
]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.1 || ^3.0"
psycopg2-binary = "^2.8"

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
coverage = "^4.5"
dj-database-url = "^0.5.0"
isort = "^4.3"
pylint = "^2.4"
pylint-django = "^2.0"
pytest = "^3.0"
pytest-cov = "^2.7"
pytest-django = "^3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
