# Generated by Django 2.0.5 on 2019-11-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localcosmos_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='webapp_zip_url',
            field=models.URLField(null=True),
        ),
    ]
