dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: Uj31a7NmgNvR00r2MKX7axQ7T9cYgB8kY0P1QqBdmXbKlVK0SPUs0EBz1rwXDFfKqKo4SckukeR7UmBn7xbzBiUckRc4DKRYAqr13WBbQJO2PMCjhfplPLJq2RPn3v2nYIRAIfP1tAGTXwVSmfsKGdl6X98xN7s42OauJ9jkAtfr7YQaiRTZ/+1dnDXwfvQZk7wrOHQn3gNkMbFIPEBdcvCjDbiIlyqfWEASLCRDP4f8ocmiye3tml58ua2QtnjqUB98wQZHUvvrS5Q0yYGc8Fd/sKoz+uc+Kd3goWOOmPnlnFzFfSBt7cDViX7k8N9wzp26QYAlznFaaCiUv8cMylZ8D7TwlwY7M1zeER47PCBUZUP9YgPPBhfTogJ/bNx+xwU57Dxt8MwwdKJXkxo35Id7tZu3h544KoiZH7ANaTf1NTo1anDp0devmT8fI7dWx1cczPWP/NzNc1vRr5OvghZZ6cZz1F7yRluj9aqFzXg1tCnm+7d6MtxlG54IOzAwvKe4qoQAEBQlVqgXtX62nRcGxZwFtjmWQpRyDuIskkCH7Tz/CPH0H97UrTatyazUulh0FrE6eTgOc2COCbCXULN7kaKHjlBjHjw3EtR9kuTaGzU5KAOm4YdJD13y33TOPJq+pnvbuDZEY54R0ATU1L4M20tN6YQXkzwr4PILSPo=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_avrprog.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-avrprog --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
