
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-16T22:40:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "707567b5d346f9fc8f142c6c5969cf6b37f7574c",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
