[tool.poetry]
name = "flake8-boto3"
version = "0.1.1"
description = "r2c flake8 check"
authors = ["R2C <hello@returntocorp.com>"]
readme = "README.md"
homepage = "https://r2c.dev"
classifiers=[
  "Programming Language :: Python :: 3",
  "License :: Other/Proprietary License",
  "Operating System :: OS Independent",
]
packages = [
  { include = "flake8_boto3"},
]
exclude = ["tests/**"]

[tool.poetry.dependencies]
python = "^3.7"
flake8 = "^3.7.9"
pytest = "^5.3.0"
boto3 = "^1.10.21"
astunparse = "^1.6.2"

[tool.poetry.plugins]
[tool.poetry.plugins."flake8.extension"]
r2c-avoid-hardcoded-access-token = "flake8_boto3.auth:CheckHardcodedAccessTokens"
r2c-boto3-dont-use-deprecated-api = "flake8_boto3.deprecated:CheckDeprecatedAPI"
r2c-use-boto3-over-boto = "flake8_boto3.boto_import:CheckInvalidBotoImport"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
