
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-19T15:29:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ec34aa9149aaee096dd19019d8c0d5b81061ae3",
 "version": "v0.16.2a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
