[tool.poetry]
name = "hoist"
version = "0.1.2"
description = ""
authors = ["Shady Rafehi <shadyrafehi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
websockets = "^7.0"
toml = "^0.10.0"
jinja2 = "^2.10"
aiohttp = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
hoist = "hoist:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

