#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='argparse_dataclass',
      version='0.1.dev0',
      description='``argparse_dataclass``',
      author='Michael V. DePalatis',
      author_email='mike@depalatis.net',
      url='https://github.com/mivade/argparse_dataclass',
      py_modules=['argparse_dataclass'],
     )
