#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['change']

package_data = \
{'': ['*']}

install_requires = \
['pyyaml']

extras_require = \
{'dev': ['pre-commit'],
 'doc': ['sphinx', 'sphinx_rtd_theme'],
 'test': ['pytest >=4.3.0', 'flake8', 'flake8-bugbear'],
 "test:implementation_name=='cpython'": ['black']}

setup(name='change-log',
      version='0.2.0',
      description='Change and Manage Package Information',
      author='Eileen Kuehn, Max Fischer',
      author_email='mainekuehn@gmail.com',
      url='https://github.com/mainekuehn/change-log',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
     )
