# coding: utf-8
# Generated by setup.py for PyCBC on 2019-11-18 21:32:28 +0000.

version = '1.14.4'
date = '2019-11-18 20:53:14 +0000'
release = True
last_release = '1.14.4'

git_hash = '60502a8a097e0692c9930cc9f3f0816e46eb6c4b'
git_branch = 'None'
git_tag = 'v1.14.4'
git_author = 'Ian Harry <ian.harry@ligo.org>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2019-11-18 21:32:28 +0000'
git_verbose_msg = """Version: 1.14.4
Branch: None
Tag: v1.14.4
Id: 60502a8a097e0692c9930cc9f3f0816e46eb6c4b
Builder: Travis CI User <travis@example.org>
Build date: 2019-11-18 21:32:28 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
