# Generated by Django 2.2.7 on 2019-11-21 23:08

from django.db import migrations, models
import lockmgr.models


class Migration(migrations.Migration):

    dependencies = [
        ('lockmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='locked_until',
            field=models.DateTimeField(blank=True, default=lockmgr.models.default_lock_expiry, null=True),
        ),
    ]
