__version__ = "0.5"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.5)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e164be6514f4ff29531d3d4397b5452f7d1a6fcf'
__git_head_subject__ = u'Finished Release v0.5'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2019-11-18 15:29:37'
