# Generated by Django 2.2.2 on 2019-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrails', '0009_auto_20190712_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='hoofd_object',
            field=models.URLField(help_text='De URL naar het hoofdobject van een component.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='resource_url',
            field=models.URLField(help_text='De URL naar het object.', max_length=2000),
        ),
    ]
