# Generated by Django 2.2.2 on 2019-10-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audittrails', '0010_auto_20190926_0900'),
        ('audittrails', '0010_audittrail_request_id'),
    ]

    operations = [
    ]
