- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - release-notes-jobs-python3
