name: GloVe word embeddings
website: http://nlp.stanford.edu/projects/glove/
license: Public Domain Dedication and License
abtract: True
tags:
  - word embeddings
papers:
  technical description: http://nlp.stanford.edu/pubs/glove.pdf
description: |
  GloVe is an unsupervised learning algorithm for obtaining vector representations for words.
  Training is performed on aggregated global word-word co-occurrence statistics from a corpus,
  and the resulting representations showcase interesting linear substructures of the word vector space.
...

---
id: 6b
description: Trained on Wikipedia 2014 + Gigaword 5
download: !@/archive:Zip
  url: http://nlp.stanford.edu/data/glove.6B.zip
size: 822M
statistics:
  tokens: 6G
  vocabulary: 400K
  cased: false
---
id: 6b.50
statistics: [dimension: 50]
download: !@/single:DatasetPath
  reference: !dataset .6b
  path: "glove.6B.50d.txt"
...
---
id: 6b.100
statistics: [dimension: 100]
download: !@/single:DatasetPath
  reference: !dataset .6b
  path: "glove.6B.100d.txt"
...
---
id: 6b.200
statistics: [dimension: 200]
download: !@/single:DatasetPath
  reference: !dataset .6b
  path: "glove.6B.200d.txt"
...
...
---
id: 6b.300
statistics: [dimension: 200]
download: !@/single:DatasetPath
  reference: !dataset .6b
  path: "glove.6B.200d.txt"
...


---
id: 42b
description: Trained on Common Crawl
download: !@/single:File
  url: http://nlp.stanford.edu/data/glove.42B.300d.zip
size: 2.03G
statistics:
  cased: true
  tokens: 840G
  vocabulary: 2.2M
  dimension: 300
...

---
id: 840b
description: Trained on Common Crawl
download: !@/single:File
  url: http://nlp.stanford.edu/data/glove.840B.300d.zip
size: 2.03G
statistics:
  cased: true
  tokens: 840G
  vocabulary: 2.2M
  dimension: 300
