language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov

# Run the unit test
script:
  - python run_tests.py

after_success:
  - coverage combine
  - codecov