#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['rtm']

package_data = \
{'': ['*'], 'rtm': ['containers/*', 'main/*', 'validate/*']}

install_requires = \
['click', 'openpyxl', 'colorama', 'requests']

entry_points = \
{'console_scripts': ['rtm = rtm.main.cli:main']}

setup(name='dps-rtm',
      version='0.1.27',
      description='Validate a Requirements Trace Matrix',
      author='Jonathan Chukinas',
      author_email='chukinas@gmail.com',
      url='https://github.com/jonathanchukinas/fdr',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
