name: thelper
channels:
  - pytorch
  - conda-forge
dependencies:
  - albumentations
  - cython
  - ddt
  - gitdb
  - gitpython
  - lz4
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pip
  - pytorch<1.3
  - pyyaml
  - scipy
  - scikit-learn
  - six
  - torchvision
  - tqdm
  - umap-learn
  - pip:
    - augmentor
    - h5py
    - imgaug==0.2.5
    - opencv-python
    - pynput
    - tensorboardX
