[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "ipx800"
dist-name = "gce-ipx800"
author = "Marc-Aurèle Brothier"
author-email = "m@brothier.org"
maintainer = "Marc-Aurèle Brothier"
home-page = "https://github.com/marcaurele/py-ipx800"
description-file = "README.md"
keywords = "ipx800, GCE-Electronics, GCE, home-automation"
requires = ["requests"]
requires-python = ">=3.5"
classifiers = ["Topic :: Home Automation",
               "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
               "License :: OSI Approved :: Apache Software License",
               "Operating System :: OS Independent",
	       "Programming Language :: Python",
	       "Programming Language :: Python :: 3",
	       "Programming Language :: Python :: 3.5",
	       "Programming Language :: Python :: 3.6",
	       "Programming Language :: Python :: 3.7",
	       "Programming Language :: Python :: 3.8"]

