
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-16T10:53:17-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1b17c9eb87eaaa0cfd49fafda33c13ea4d8fa3b",
 "version": "0+untagged.614.gc1b17c9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
