package:
  name: 'tofu'
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/ToFuProject/tofu.git
  #git_branch: {{ environ['TRAVIS_BRANCH'] }}
  git_rev: {{ environ['REV'] }}
  # "patches:" might be the answer for clang compilers ?

build:
  script_env:
    #   - REV
    - VERSION
    - TRAVIS_BRANCH
    - CONDA_BLD_PATH

requirements:

  # build: necessary for build.sh
  # here same as run, as we are using cython
  build:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - scipy
    - matplotlib
    - cython >=0.26
    - nose
    - pygments


  # for running the library
  run:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - scipy
    - matplotlib
    - cython >=0.26
    - nose
    - pygments

test:
  requires:
    - nose
  imports:
    - tofu.geom

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE.txt
  summary: Tomography for Fusion

# conda build -c tofuproject conda_recipe/
