
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-22T18:21:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f642d24aa5563e8fca25c8fbadb3a97643d163e4",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
