tags: [ documents, text, html, web ]
type: warc
warc-version: 0.18
namespaces:
  clueweb: gov.nist.trec.clueweb

data:
  2009.adhoc:
    url: http://trec.nist.gov/data/web09.html
    documents: !dataset clueweb!09b
    handler: trec.adhoc/task
    subdatasets:
      topics: 

  # -
  #   id: ["3", "1994"]
  #   handler: trec.adhoc/task
  #   description: "Ad-hoc task of TREC 3 (1994)"
  #   documents: !dataset ".1.documents"
  #   topics: !dataset ".3.topics"
  #   qrels: !dataset ".3.qrels"
