on: release
name: Release to PyPi
jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: tag-filter
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: check
      uses: ross/python-actions/setup-py/3.7@master
      with:
        args: check
    - name: sdist
      uses: ross/python-actions/setup-py/3.7@master
      with:
        args: sdist
    - name: upload
      uses: ross/python-actions/twine@master
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      with:
        args: upload ./dist/sunpy-sphinx-theme-*.tar.gz
