

class Corners():
    TOP_RIGHT_THICK = '┓'
    TOP_RIGHT_THIN = '┐'
    TOP_RIGHT_THICK_TOP = '┑'
    TOP_RIGHT_THICK_RIGHT = '┒'
    TOP_RIGHT_ROUNDED = '╮'
    TOP_RIGHT_FILLED = '▖'

    TOP_LEFT_THICK = '┏'
    TOP_LEFT_THIN = '┌'
    TOP_LEFT_THICK_TOP = '┍'
    TOP_LEFT_THICK_LEFT = '┎'
    TOP_LEFT_ROUNDED = '╭'
    TOP_LEFT_FILLED = '▗'

    BOTTOM_RIGHT_THICK = '┛'
    BOTTOM_RIGHT_THIN = '┘'
    BOTTOM_RIGHT_THICK_RIGHT = '┚'
    BOTTOM_RIGHT_THICK_BOTTOM = '┙'
    BOTTOM_RIGHT_ROUNDED = '╯'
    BOTTOM_RIGHT_FILLED = '▘'

    BOTTOM_LEFT_THICK = '┗'
    BOTTOM_LEFT_THIN = '└'
    BOTTOM_LEFT_THICK_LEFT = '┖'
    BOTTOM_LEFT_THICK_BOTTOM = '┕'
    BOTTOM_LEFT_ROUNDED = '╰'
    BOTTOM_LEFT_FILLED = '▝'


class Horizontals():
    HORIZ_THIN = '─'
    HORIZ_THIN_DOTTED_TWO = '╌'
    HORIZ_THIN_DOTTED_THREE = '┄'
    HORIZ_THIN_DOTTED_FOUR = '┈'

    HORIZ_THICK = '━'
    HORIZ_THICK_DOTTED_TWO = '╍'
    HORIZ_THICK_DOTTED_THREE = '┅'
    HORIZ_THICK_DOTTED_FOUR = '┉'

    HORIZ_DOUBLE = '═'

    HORIZ_TOP_FILLED = '▄'
    HORIZ_BOTTOM_FILLED = '▀'
    HORIZ_MIDDLE_FILLED = '█'

    HORIZ_DASH_DOWN_THIN = '┬'
    HORIZ_DASH_DOWN_THICK = '┳'
    HORIZ_DASH_DOWN_THICK_LEFT = '┭'
    HORIZ_DASH_DOWN_THICK_RIGHT = '┮'
    HORIZ_DASH_DOWN_THICK_DOWN = '┰'
    HORIZ_DASH_DOWN_THICK_THIN_LEFT = '┲'
    HORIZ_DASH_DOWN_THICK_THIN_RIGHT = '┱'
    HORIZ_DASH_DOWN_THICK_THIN_DOWN = '┯'

    HORIZ_DASH_UP_THIN = '┴'
    HORIZ_DASH_UP_THICK = '┻'
    HORIZ_DASH_UP_THICK_LEFT = '┵'
    HORIZ_DASH_UP_THICK_RIGHT = '┶'
    HORIZ_DASH_UP_THICK_UP = '┸'
    HORIZ_DASH_UP_THICK_THIN_LEFT = '┺'
    HORIZ_DASH_UP_THICK_THIN_RIGHT = '┹'
    HORIZ_DASH_UP_THICK_THIN_UP = '┷'


class Verticals():
    VERT_THIN = '│'
    VERT_THIN_DOTTED_TWO = '╎'
    VERT_THIN_DOTTED_THREE = '┆'
    VERT_THIN_DOTTED_FOUR = '┊'

    VERT_THICK = '┃'
    VERT_THICK_DOTTED_TWO = '╏'
    VERT_THICK_DOTTED_THREE = '┇'
    VERT_THICK_DOTTED_FOUR = '┋'

    VERT_DOUBLE = '║'
    
    VERT_RIGHT_FILLED = '▌'
    VERT_LEFT_FILLED = '▐'
    VERT_MIDDLE_FILLED = '█'

    VERT_DASH_RIGHT_THIN = '├'
    VERT_DASH_RIGHT_THICK = '┣'
    VERT_DASH_RIGHT_THICK_RIGHT = '┝'
    VERT_DASH_RIGHT_THICK_UP = '┞'
    VERT_DASH_RIGHT_THICK_DOWN = '┟'
    VERT_DASH_RIGHT_THICK_THIN_RIGHT = '┠'
    VERT_DASH_RIGHT_THICK_THIN_DOWN = '┡'
    VERT_DASH_RIGHT_THICK_THIN_UP = '┢'

    VERT_DASH_LEFT_THIN = '┤'
    VERT_DASH_LEFT_THICK = '┫'
    VERT_DASH_LEFT_THICK_LEFT = '┥'
    VERT_DASH_LEFT_THICK_UP = '┦'
    VERT_DASH_LEFT_THICK_DOWN = '┧'
    VERT_DASH_LEFT_THICK_THIN_LEFT = '┨'
    VERT_DASH_LEFT_THICK_THIN_DOWN = '┩'
    VERT_DASH_LEFT_THICK_THIN_UP = '┪'


class Middles():
    MIDDLE_THIN = '┼'
    MIDDLE_THICK = '╋'
    MIDDLE_FILLED = '█'

    MIDDLE_THICK_LEFT = '┽'
    MIDDLE_THICK_RIGHT = '┾'
    MIDDLE_THICK_UP = '╀'
    MIDDLE_THICK_DOWN = '╁'

    MIDDLE_THICK_HORIZ = '┿'
    MIDDLE_THICK_VERT = '╂'

    MIDDLE_THICK_UP_LEFT = '╃'
    MIDDLE_THICK_UP_RIGHT = '╄'
    MIDDLE_THICK_DOWN_LEFT = '╅'
    MIDDLE_THICK_DOWN_RIGHT = '╆'

    MIDDLE_THICK_THIN_DOWN = '╇'
    MIDDLE_THICK_THIN_UP = '╈'
    MIDDLE_THICK_THIN_RIGHT = '╉'
    MIDDLE_THICK_THIN_LEFT = '╊'
