
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-22T20:29:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e24237518935bdfe86775130ca945b48543a4264",
 "version": "0.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
