#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['jaeger_browser']

package_data = \
{'': ['*']}

install_requires = \
['jaeger-client',
 'uvicorn',
 'starlette',
 'mypy-extensions',
 'typing_extensions']

entry_points = \
{'console_scripts': ['jaeger-browser = jaeger_browser:main']}

setup(name='jaeger_browser',
      version='1.0.1',
      description='Python HTTP server to record traces from the browser.',
      author='Saul Shanabrook',
      author_email='saul@quansight.com',
      url='https://github.com/Quansight/jaeger-browser',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
