# Generated by Django 2.2 on 2019-11-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_system', '0003_menutop_link_view_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutop',
            name='superuser_only',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
