# Generated by Django 2.2 on 2019-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_system', '0005_menuapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True)),
                ('social_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
