# Generated by Django 2.2 on 2019-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_system', '0006_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
