# Generated by Django 2.2 on 2019-11-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_system', '0008_delete_websiteinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuApp',
            new_name='App',
        ),
        migrations.RenameModel(
            old_name='MenuTop',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='SocialLink',
            new_name='Social',
        ),
    ]
