[tool.poetry]
name = "regex2d"
version = "0.1.0"
description = "2 dimensional regex engine for describing image languages"
authors = ["Arjoonn Sharma <arjoonn.94@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
