language: python
python:
- 3.7
script:
- pip install yapf
- diffs=$(yapf -dr --style=yapf.ini ./thunderbolt)
- if [ -n "$diffs" ]; then exit 1; fi
- python setup.py install
- python -m unittest discover -s ./test/
deploy:
  on:
    branch: master
    tags: true
  provider: pypi
  user: vaaaaanquish
  distributions: "sdist bdist_wheel"
  server: https://upload.pypi.org/legacy/
  skip_existing: true
  password:
    secure: pTHDySZYFDHEKM3kTDShANI+eavTVZTirgZll5uBEiH6/8Bbr/9VQ6amDAFKsNA2kolYh0/zaU6ty8+ejosxbAayiadDi+mv6/b6QIsOmpheFkHtkO12lO3kT8w7D97wmMI/JDH/bfdo3YwysDnUj0AHh06wqypRexmgG+wcB0/+KTREP16ZBcT8TAPZtpt41sW3j5PT6+EubTA3kULn9LNZQbGUCVZ6F0RnbF0JM1j7I6UBGp3gGbR7WJZ7+tJST/hN36O/2cxh4AJDUk2gTlgq3bvBQeAtcXFaAqz4r0s5eBNOBJe1gIkoXrL0xLhvCU6JYTnW0Dg6Zo/BC1ZwKJ9JmUKKT80jhU3psuBfwc36DxGcMmmX/72jVO1F5hgjGtgiLZURqUvIKUc3AePhUZFXn2VhNqtN9kBIa7XTkeX4K+NHG+jAhrdmVc7zlBotdQDCd00bjJTS8InYMR2sqnQA8yR5bnbtJrX59/eImO41lIpl57aSaXZR/oY+kzZi8Sk4nFKjeAeYSFwO67qy4keBa/qHz5S5le2ch8kyphjTWHc+FkYQq6OGQaektFEoo+0ZBjP9/hhXwhcQGcxy7Or2FrN4BM0IxrvcmCSNqsY+MTgZeKJInT2P0waY9ZY3ihj15eV7F1EccpZi+oxp6k1/c69SRf3lRr/TXOYsbqI=
