[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "phsp"
author = "Paulo Henrique Silva"
author-email = "ph.silva@gmail.com"
home-page = "https://github.com/phsilva/ph-sample-package"
