[tool.poetry]
name = "pastebin_archiver"
version = "0.2.0"
description = "Archive all public posts from Pastebin.com"
license = "MIT"
authors = ["Jon Pavelich <pypi@jonpavelich.com>"]
readme = "README.md"
repository = "https://gitlab.com/jonpavelich/pastebin-archiver"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
sqlalchemy = "^1.3"
apscheduler = "^3.6"
psycopg2-binary = {version = "^2.8", optional = true}

[tool.poetry.extras]
pgsql = ["psycopg2-binary"]

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
flake8 = "^3.7"
flake8-bugbear = "^19.8"

[tool.poetry.scripts]
pastebin-archiver = "pastebin_archiver.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
