[tool.poetry]
name = "pro-gan-pytorch"
version = "0.1.1"
description = "various GANS training package"
authors = ["Sindhura <sindhura.k@fractal.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "3.6.9"
albumentations = "^0.4.2"
easydict = "^1.9"
imageio = "^2.6"
opencv-python = "^4.1"
pandas = "0.25.2"
PyYAML = "5.1.2"
scikit-image = "0.16.2"
torch = "1.3.0"
tqdm = "4.36.1"
urllib3 = "1.25.6"
torchvision = "0.4.1"
torchnet = "^0.0.4"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
train = "pro_gan_pytorch.train:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"