dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: vbm1F3ytAJ5KowFopPDIAaOyUe1bxvBG6+9iq5M1eLcz7cGzO+bFYDYAc6mSvNzWTxfJj0OhAacLYdvvl+LuEbBpFAABRmC0klbWAHwPDHO49eMcT4F2Optrc4HmEwyA+7vwlYoWJIyANz9gbAmVhiBoXw0bMTb+kn9465v3NR86XVTnKnPeAMtsXWgEw3YHdaLa93tFEiMN73bntlQXMSbxCqAqTJUqe8ekGuaezLmR7VtfTeYN6jvGNMZuPYGA/F8Gi91qXuqmQmZLhQ9hc4KVuq1hMudDHlqNeVzw9/rRPKnoO93UuGVXuJVosCdgU/STVCpd13Lqa97XnozeKxWo10PFdwlrc7vlebqlZAw9If2tR3KhKDhDxakZHlXdxnPyFGK43csIOjO/ctjv+/A2pga6ys+VcdM9uDONkGdCh2AvYlN+yezR11GR01LRMOyeF0g5bB+FzNh6V69F3UuD4ydtPpLuHVuwWvGkDTiwfIhkNF3BVTohqpDJadCj+jJgw6271PjET1PXo+VlT3S+gCqD527lAXaxyNrIvTr9iupJGnhOBdU5EBepbAxHgAyNrqiL/vS0kH4LuxSFGYPCnxHx4Ep8LAB0zcDneJFHrbhIeqJipR+MY8PnDNGXX+5pmrb1++OS8oQZPFesn0Ap8M1jfAw9UDe+H8WpnIM=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_hid/*.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-hid --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
