
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-02T18:04:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5b457a44b609b9da104897a7ea46c4f62cc42d4",
 "version": "4.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
