
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-19T00:08:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3c00e6a3203bde5e53de67e65312fa5747d6735",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
