dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: Pw3bUEUnkp1eMREw/z1cMbyten2K5FgSrpqva3r6PLAcQDtAgItMgsR1sklquOPebaqDS09Xjum3L7VFG2QIBpUWpcicncdfYryW+aJF7jYC6wkwT+0mFt0PNSi1T+eMPuQsy+4rSPGwEa4R+mbgCX56lTHvcWjdn5H2/SeGBb7aFcaE6f+CwhczpXvmG6VAywjEc+6js0A1hkT10R8W4Gz0WcyK7jEekIa2NQu24di7E+kyUUWsWzlvMbMmLVOTCZWlxVR6l02RYy/OhZOgefGgSbSJUKkmRjrytrVaCXVp5KQrbZkjUlnxVkh0JJ/fAShEQ6gft+pdUeMpxIlhkIqIdQOLhHzsOrV6yDNa6nH4CcOTUhjXtLCO1pp+IextDC+1d24lIzTu/rA0XzpbSSKaPLkFXip4/ci6p4FEZ6IReYxYdf+aREsU7ZmBJS+Kopcg+jjQzKf++D3VYIHtpGmQWNtg6sTDe1dnBK0nOLrCDHUAJnpruWTiJsDTSnr/Yzqf3Q6Hemb+yvZHVfQvmW+5/EnJcYZHao90XV/ajmVIwpdZW+TMRQamcxCBzaFzCLxT2G5KG4eDitX5x+3aQw72LrUzsBkE1gqnv8jNLRCEgxiikgLCnLbJ96LRpOr8ovriEX4nwNYnqS48yV52s5iqnLkTxq2I88nTjVPoRmY=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_gps.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-gps --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
