# coding: utf-8

"""
    Spotii Billing API

    API for Billing  # noqa: E501

    OpenAPI spec version: v1.0
    Contact: hello@nuclearo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import spotii_billing_client
from billing.installments_api import InstallmentsApi  # noqa: E501
from spotii_billing_client.rest import ApiException


class TestInstallmentsApi(unittest.TestCase):
    """InstallmentsApi unit test stubs"""

    def setUp(self):
        self.api = billing.installments_api.InstallmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_installments_estimate_create(self):
        """Test case for installments_estimate_create

        """
        pass

    def test_installments_installments_create(self):
        """Test case for installments_installments_create

        """
        pass

    def test_installments_installments_delete(self):
        """Test case for installments_installments_delete

        """
        pass

    def test_installments_installments_list(self):
        """Test case for installments_installments_list

        """
        pass

    def test_installments_installments_read(self):
        """Test case for installments_installments_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
