[tool.poetry]
name = "hrpy"
version = "0.2.2"
description = "hr but written in python"
authors = ["John Naylor <jonaylor89@gmail.com>"]
license = "MIT"

readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
hr = 'hrpy.hr:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
