
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-02T11:25:46-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f949f14645d728f4b750a8f4a23ab6e84ad3ae29",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
