
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-22T10:32:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5f1b37fc1fe0272f418b3c3e9fd7aaf12ba2378",
 "version": "0.25.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
