
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9281be92f0e52a14085841344a509f7808efcfe1",
 "version": "1.1.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
