# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class Console(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text
    prompt = ... # type: typing___Text
    busy = ... # type: builtin___bool

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        prompt : typing___Optional[typing___Text] = None,
        busy : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Console: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"busy",u"id",u"prompt"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"busy",b"busy",u"id",b"id",u"prompt",b"prompt"]) -> None: ...

class ConsoleList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def consoles(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Console]: ...

    def __init__(self,
        *,
        consoles : typing___Optional[typing___Iterable[Console]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ConsoleList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"consoles"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"consoles",b"consoles"]) -> None: ...

class ConsoleOutputList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    total = ... # type: builtin___int
    count = ... # type: builtin___int

    @property
    def output(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ConsoleOutput]: ...

    def __init__(self,
        *,
        total : typing___Optional[builtin___int] = None,
        count : typing___Optional[builtin___int] = None,
        output : typing___Optional[typing___Iterable[ConsoleOutput]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ConsoleOutputList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"count",u"output",u"total"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"count",b"count",u"output",b"output",u"total",b"total"]) -> None: ...

class ConsoleOutput(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    output = ... # type: typing___Text

    def __init__(self,
        *,
        output : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ConsoleOutput: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"output"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"output",b"output"]) -> None: ...
