# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metasploit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import models_pb2 as models__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metasploit.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10metasploit.proto\x1a\x0cmodels.proto\"3\n\x07\x43onsole\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x0c\n\x04\x62usy\x18\x03 \x01(\x08\")\n\x0b\x43onsoleList\x12\x1a\n\x08\x63onsoles\x18\x01 \x03(\x0b\x32\x08.Console\"Q\n\x11\x43onsoleOutputList\x12\r\n\x05total\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x1e\n\x06output\x18\x03 \x03(\x0b\x32\x0e.ConsoleOutput\"\x1f\n\rConsoleOutput\x12\x0e\n\x06output\x18\x01 \x01(\t2\xa3\x02\n\nMetasploit\x12*\n\x08ListJobs\x12\r.EmptyRequest\x1a\r.EmptyMessage\"\x00\x12,\n\x0cListExploits\x12\x0b.Pagination\x1a\r.EmptyMessage\"\x00\x12-\n\x0cListConsoles\x12\r.EmptyRequest\x1a\x0c.ConsoleList\"\x00\x12*\n\rCreateConsole\x12\r.EmptyRequest\x1a\x08.Console\"\x00\x12(\n\x0bStopConsole\x12\x08.Console\x1a\r.EmptyMessage\"\x00\x12\x36\n\x11ListConsoleOutput\x12\x0b.Pagination\x1a\x12.ConsoleOutputList\"\x00\x62\x06proto3')
  ,
  dependencies=[models__pb2.DESCRIPTOR,])




_CONSOLE = _descriptor.Descriptor(
  name='Console',
  full_name='Console',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Console.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prompt', full_name='Console.prompt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='busy', full_name='Console.busy', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=85,
)


_CONSOLELIST = _descriptor.Descriptor(
  name='ConsoleList',
  full_name='ConsoleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consoles', full_name='ConsoleList.consoles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=128,
)


_CONSOLEOUTPUTLIST = _descriptor.Descriptor(
  name='ConsoleOutputList',
  full_name='ConsoleOutputList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='ConsoleOutputList.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='ConsoleOutputList.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='ConsoleOutputList.output', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=211,
)


_CONSOLEOUTPUT = _descriptor.Descriptor(
  name='ConsoleOutput',
  full_name='ConsoleOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='ConsoleOutput.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=244,
)

_CONSOLELIST.fields_by_name['consoles'].message_type = _CONSOLE
_CONSOLEOUTPUTLIST.fields_by_name['output'].message_type = _CONSOLEOUTPUT
DESCRIPTOR.message_types_by_name['Console'] = _CONSOLE
DESCRIPTOR.message_types_by_name['ConsoleList'] = _CONSOLELIST
DESCRIPTOR.message_types_by_name['ConsoleOutputList'] = _CONSOLEOUTPUTLIST
DESCRIPTOR.message_types_by_name['ConsoleOutput'] = _CONSOLEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Console = _reflection.GeneratedProtocolMessageType('Console', (_message.Message,), {
  'DESCRIPTOR' : _CONSOLE,
  '__module__' : 'metasploit_pb2'
  # @@protoc_insertion_point(class_scope:Console)
  })
_sym_db.RegisterMessage(Console)

ConsoleList = _reflection.GeneratedProtocolMessageType('ConsoleList', (_message.Message,), {
  'DESCRIPTOR' : _CONSOLELIST,
  '__module__' : 'metasploit_pb2'
  # @@protoc_insertion_point(class_scope:ConsoleList)
  })
_sym_db.RegisterMessage(ConsoleList)

ConsoleOutputList = _reflection.GeneratedProtocolMessageType('ConsoleOutputList', (_message.Message,), {
  'DESCRIPTOR' : _CONSOLEOUTPUTLIST,
  '__module__' : 'metasploit_pb2'
  # @@protoc_insertion_point(class_scope:ConsoleOutputList)
  })
_sym_db.RegisterMessage(ConsoleOutputList)

ConsoleOutput = _reflection.GeneratedProtocolMessageType('ConsoleOutput', (_message.Message,), {
  'DESCRIPTOR' : _CONSOLEOUTPUT,
  '__module__' : 'metasploit_pb2'
  # @@protoc_insertion_point(class_scope:ConsoleOutput)
  })
_sym_db.RegisterMessage(ConsoleOutput)



_METASPLOIT = _descriptor.ServiceDescriptor(
  name='Metasploit',
  full_name='Metasploit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=247,
  serialized_end=538,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListJobs',
    full_name='Metasploit.ListJobs',
    index=0,
    containing_service=None,
    input_type=models__pb2._EMPTYREQUEST,
    output_type=models__pb2._EMPTYMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListExploits',
    full_name='Metasploit.ListExploits',
    index=1,
    containing_service=None,
    input_type=models__pb2._PAGINATION,
    output_type=models__pb2._EMPTYMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListConsoles',
    full_name='Metasploit.ListConsoles',
    index=2,
    containing_service=None,
    input_type=models__pb2._EMPTYREQUEST,
    output_type=_CONSOLELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateConsole',
    full_name='Metasploit.CreateConsole',
    index=3,
    containing_service=None,
    input_type=models__pb2._EMPTYREQUEST,
    output_type=_CONSOLE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopConsole',
    full_name='Metasploit.StopConsole',
    index=4,
    containing_service=None,
    input_type=_CONSOLE,
    output_type=models__pb2._EMPTYMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListConsoleOutput',
    full_name='Metasploit.ListConsoleOutput',
    index=5,
    containing_service=None,
    input_type=models__pb2._PAGINATION,
    output_type=_CONSOLEOUTPUTLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METASPLOIT)

DESCRIPTOR.services_by_name['Metasploit'] = _METASPLOIT

# @@protoc_insertion_point(module_scope)
