# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datetime_subset.ui'
#
# Created: Wed Aug  9 16:27:31 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DateTimeSubsetDialog(object):
    def setupUi(self, DateTimeSubsetDialog):
        DateTimeSubsetDialog.setObjectName("DateTimeSubsetDialog")
        DateTimeSubsetDialog.resize(276, 225)
        self.gridLayout = QtGui.QGridLayout(DateTimeSubsetDialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 3)
        self.useAllData = QtGui.QRadioButton(DateTimeSubsetDialog)
        self.useAllData.setChecked(True)
        self.useAllData.setObjectName("useAllData")
        self.gridLayout.addWidget(self.useAllData, 0, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(DateTimeSubsetDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.durationLabel = QtGui.QLabel(DateTimeSubsetDialog)
        self.durationLabel.setEnabled(False)
        self.durationLabel.setObjectName("durationLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.durationLabel)
        self.duration = QtGui.QLabel(DateTimeSubsetDialog)
        self.duration.setEnabled(False)
        self.duration.setObjectName("duration")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.duration)
        self.endLabel = QtGui.QLabel(DateTimeSubsetDialog)
        self.endLabel.setEnabled(False)
        self.endLabel.setObjectName("endLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.endLabel)
        self.startLabel = QtGui.QLabel(DateTimeSubsetDialog)
        self.startLabel.setEnabled(False)
        self.startLabel.setObjectName("startLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.startLabel)
        self.endDateTime = QtGui.QDateTimeEdit(DateTimeSubsetDialog)
        self.endDateTime.setEnabled(False)
        self.endDateTime.setWrapping(True)
        self.endDateTime.setObjectName("endDateTime")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.endDateTime)
        self.startDateTime = QtGui.QDateTimeEdit(DateTimeSubsetDialog)
        self.startDateTime.setEnabled(False)
        self.startDateTime.setWrapping(True)
        self.startDateTime.setObjectName("startDateTime")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.startDateTime)
        self.gridLayout.addLayout(self.formLayout_2, 3, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.useSubset = QtGui.QRadioButton(DateTimeSubsetDialog)
        self.useSubset.setObjectName("useSubset")
        self.gridLayout.addWidget(self.useSubset, 2, 0, 1, 3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.allStartLabel = QtGui.QLabel(DateTimeSubsetDialog)
        self.allStartLabel.setObjectName("allStartLabel")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.allStartLabel)
        self.allStart = QtGui.QLabel(DateTimeSubsetDialog)
        self.allStart.setObjectName("allStart")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.allStart)
        self.allEndLabel = QtGui.QLabel(DateTimeSubsetDialog)
        self.allEndLabel.setObjectName("allEndLabel")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.allEndLabel)
        self.allEnd = QtGui.QLabel(DateTimeSubsetDialog)
        self.allEnd.setObjectName("allEnd")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.allEnd)
        self.allDurationLabel = QtGui.QLabel(DateTimeSubsetDialog)
        self.allDurationLabel.setObjectName("allDurationLabel")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.allDurationLabel)
        self.allDuration = QtGui.QLabel(DateTimeSubsetDialog)
        self.allDuration.setObjectName("allDuration")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.allDuration)
        self.gridLayout.addLayout(self.formLayout_4, 1, 1, 1, 2)

        self.retranslateUi(DateTimeSubsetDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DateTimeSubsetDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DateTimeSubsetDialog.reject)
        QtCore.QObject.connect(self.useSubset, QtCore.SIGNAL("toggled(bool)"), self.startLabel.setEnabled)
        QtCore.QObject.connect(self.useSubset, QtCore.SIGNAL("toggled(bool)"), self.startDateTime.setEnabled)
        QtCore.QObject.connect(self.useSubset, QtCore.SIGNAL("toggled(bool)"), self.endLabel.setEnabled)
        QtCore.QObject.connect(self.useSubset, QtCore.SIGNAL("toggled(bool)"), self.endDateTime.setEnabled)
        QtCore.QObject.connect(self.useSubset, QtCore.SIGNAL("toggled(bool)"), self.durationLabel.setEnabled)
        QtCore.QObject.connect(self.useSubset, QtCore.SIGNAL("toggled(bool)"), self.duration.setEnabled)
        QtCore.QObject.connect(self.useAllData, QtCore.SIGNAL("toggled(bool)"), self.allStartLabel.setEnabled)
        QtCore.QObject.connect(self.useAllData, QtCore.SIGNAL("toggled(bool)"), self.allStart.setEnabled)
        QtCore.QObject.connect(self.useAllData, QtCore.SIGNAL("toggled(bool)"), self.allEndLabel.setEnabled)
        QtCore.QObject.connect(self.useAllData, QtCore.SIGNAL("toggled(bool)"), self.allEnd.setEnabled)
        QtCore.QObject.connect(self.useAllData, QtCore.SIGNAL("toggled(bool)"), self.allDurationLabel.setEnabled)
        QtCore.QObject.connect(self.useAllData, QtCore.SIGNAL("toggled(bool)"), self.allDuration.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DateTimeSubsetDialog)
        DateTimeSubsetDialog.setTabOrder(self.useAllData, self.useSubset)
        DateTimeSubsetDialog.setTabOrder(self.useSubset, self.startDateTime)
        DateTimeSubsetDialog.setTabOrder(self.startDateTime, self.endDateTime)
        DateTimeSubsetDialog.setTabOrder(self.endDateTime, self.buttonBox)

    def retranslateUi(self, DateTimeSubsetDialog):
        DateTimeSubsetDialog.setWindowTitle(QtGui.QApplication.translate("DateTimeSubsetDialog", "Select Data Range", None, QtGui.QApplication.UnicodeUTF8))
        self.useAllData.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "Use all data", None, QtGui.QApplication.UnicodeUTF8))
        self.durationLabel.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "0 s", None, QtGui.QApplication.UnicodeUTF8))
        self.endLabel.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "End Time (UTC):", None, QtGui.QApplication.UnicodeUTF8))
        self.startLabel.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "Start Time (UTC):", None, QtGui.QApplication.UnicodeUTF8))
        self.useSubset.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "Use data within range", None, QtGui.QApplication.UnicodeUTF8))
        self.allStartLabel.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "Start Time (UTC):", None, QtGui.QApplication.UnicodeUTF8))
        self.allStart.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "1/1/2000 12:00:00 AM", None, QtGui.QApplication.UnicodeUTF8))
        self.allEndLabel.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "End Time (UTC):", None, QtGui.QApplication.UnicodeUTF8))
        self.allEnd.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "1/1/2000 12:00:00 AM", None, QtGui.QApplication.UnicodeUTF8))
        self.allDurationLabel.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.allDuration.setText(QtGui.QApplication.translate("DateTimeSubsetDialog", "0 s", None, QtGui.QApplication.UnicodeUTF8))

