# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Oct 21 09:10:39 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MondoMainWindow(object):
    def setupUi(self, MondoMainWindow):
        MondoMainWindow.setObjectName("MondoMainWindow")
        MondoMainWindow.resize(617, 322)
        self.centralwidget = QtGui.QWidget(MondoMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.psdButton = QtGui.QPushButton(self.groupBox)
        self.psdButton.setMinimumSize(QtCore.QSize(175, 0))
        self.psdButton.setObjectName("psdButton")
        self.verticalLayout.addWidget(self.psdButton)
        self.singleChannelPsdButton = QtGui.QPushButton(self.groupBox)
        self.singleChannelPsdButton.setObjectName("singleChannelPsdButton")
        self.verticalLayout.addWidget(self.singleChannelPsdButton)
        self.singleSlicePsdButton = QtGui.QPushButton(self.groupBox)
        self.singleSlicePsdButton.setObjectName("singleSlicePsdButton")
        self.verticalLayout.addWidget(self.singleSlicePsdButton)
        self.overlaidPsdButton = QtGui.QPushButton(self.groupBox)
        self.overlaidPsdButton.setMinimumSize(QtCore.QSize(175, 0))
        self.overlaidPsdButton.setObjectName("overlaidPsdButton")
        self.verticalLayout.addWidget(self.overlaidPsdButton)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.csvButton = QtGui.QPushButton(self.groupBox_4)
        self.csvButton.setMinimumSize(QtCore.QSize(175, 0))
        self.csvButton.setObjectName("csvButton")
        self.verticalLayout_4.addWidget(self.csvButton)
        self.csvDownsampledButton = QtGui.QPushButton(self.groupBox_4)
        self.csvDownsampledButton.setMinimumSize(QtCore.QSize(175, 0))
        self.csvDownsampledButton.setObjectName("csvDownsampledButton")
        self.verticalLayout_4.addWidget(self.csvDownsampledButton)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spectrogramButton = QtGui.QPushButton(self.groupBox_2)
        self.spectrogramButton.setMinimumSize(QtCore.QSize(175, 0))
        self.spectrogramButton.setObjectName("spectrogramButton")
        self.verticalLayout_2.addWidget(self.spectrogramButton)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.timeButton = QtGui.QPushButton(self.groupBox_3)
        self.timeButton.setMinimumSize(QtCore.QSize(175, 0))
        self.timeButton.setObjectName("timeButton")
        self.verticalLayout_3.addWidget(self.timeButton)
        self.synchronousTimeButton = QtGui.QPushButton(self.groupBox_3)
        self.synchronousTimeButton.setMinimumSize(QtCore.QSize(175, 0))
        self.synchronousTimeButton.setObjectName("synchronousTimeButton")
        self.verticalLayout_3.addWidget(self.synchronousTimeButton)
        self.overlaidTimeButton = QtGui.QPushButton(self.groupBox_3)
        self.overlaidTimeButton.setMinimumSize(QtCore.QSize(175, 0))
        self.overlaidTimeButton.setObjectName("overlaidTimeButton")
        self.verticalLayout_3.addWidget(self.overlaidTimeButton)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fileInformationButton = QtGui.QPushButton(self.groupBox_5)
        self.fileInformationButton.setObjectName("fileInformationButton")
        self.verticalLayout_6.addWidget(self.fileInformationButton)
        self.rawExportButton = QtGui.QPushButton(self.groupBox_5)
        self.rawExportButton.setObjectName("rawExportButton")
        self.verticalLayout_6.addWidget(self.rawExportButton)
        self.splitFileButton = QtGui.QPushButton(self.groupBox_5)
        self.splitFileButton.setObjectName("splitFileButton")
        self.verticalLayout_6.addWidget(self.splitFileButton)
        spacerItem4 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.setStretch(1, 1)
        MondoMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MondoMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuCheckForUpdates = QtGui.QMenu(self.menuHelp)
        self.menuCheckForUpdates.setObjectName("menuCheckForUpdates")
        MondoMainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtGui.QAction(MondoMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(MondoMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAboutLibraries = QtGui.QAction(MondoMainWindow)
        self.actionAboutLibraries.setObjectName("actionAboutLibraries")
        self.actionUpdateLatestStable = QtGui.QAction(MondoMainWindow)
        self.actionUpdateLatestStable.setObjectName("actionUpdateLatestStable")
        self.actionUpdateSpecificBranch = QtGui.QAction(MondoMainWindow)
        self.actionUpdateSpecificBranch.setObjectName("actionUpdateSpecificBranch")
        self.actionUpdateSpecificCommit = QtGui.QAction(MondoMainWindow)
        self.actionUpdateSpecificCommit.setObjectName("actionUpdateSpecificCommit")
        self.actionUpdateCurrentBranch = QtGui.QAction(MondoMainWindow)
        self.actionUpdateCurrentBranch.setObjectName("actionUpdateCurrentBranch")
        self.menuFile.addAction(self.actionExit)
        self.menuCheckForUpdates.addAction(self.actionUpdateLatestStable)
        self.menuCheckForUpdates.addAction(self.actionUpdateCurrentBranch)
        self.menuCheckForUpdates.addAction(self.actionUpdateSpecificBranch)
        self.menuCheckForUpdates.addAction(self.actionUpdateSpecificCommit)
        self.menuHelp.addAction(self.menuCheckForUpdates.menuAction())
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutLibraries)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MondoMainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MondoMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MondoMainWindow)

    def retranslateUi(self, MondoMainWindow):
        MondoMainWindow.setWindowTitle(QtGui.QApplication.translate("MondoMainWindow", "Mondo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MondoMainWindow", "Frequency Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.psdButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Power Spectral Density (PSD)", None, QtGui.QApplication.UnicodeUTF8))
        self.singleChannelPsdButton.setToolTip(QtGui.QApplication.translate("MondoMainWindow", "Overlaid PSD streamlined for plotting a single channel across multiple time slices", None, QtGui.QApplication.UnicodeUTF8))
        self.singleChannelPsdButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Single Channel Overlaid PSD", None, QtGui.QApplication.UnicodeUTF8))
        self.singleSlicePsdButton.setToolTip(QtGui.QApplication.translate("MondoMainWindow", "Overlaid PSD streamlined for plotting multiple channels in a single time slice", None, QtGui.QApplication.UnicodeUTF8))
        self.singleSlicePsdButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Single Time Slice Overlaid PSD", None, QtGui.QApplication.UnicodeUTF8))
        self.overlaidPsdButton.setToolTip(QtGui.QApplication.translate("MondoMainWindow", "Ovelaid PSD for plotting arbitrary channels and time slices ", None, QtGui.QApplication.UnicodeUTF8))
        self.overlaidPsdButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Overlaid PSD", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MondoMainWindow", "Raw Data", None, QtGui.QApplication.UnicodeUTF8))
        self.csvButton.setText(QtGui.QApplication.translate("MondoMainWindow", "CSV Output", None, QtGui.QApplication.UnicodeUTF8))
        self.csvDownsampledButton.setText(QtGui.QApplication.translate("MondoMainWindow", "CSV Downsampled Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MondoMainWindow", "Time/Frequency Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.spectrogramButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Spectrogram", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MondoMainWindow", "Time Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.timeButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Time Data", None, QtGui.QApplication.UnicodeUTF8))
        self.synchronousTimeButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Synchronous Time Data", None, QtGui.QApplication.UnicodeUTF8))
        self.overlaidTimeButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Overlaid Time Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MondoMainWindow", "File Manipulation", None, QtGui.QApplication.UnicodeUTF8))
        self.fileInformationButton.setText(QtGui.QApplication.translate("MondoMainWindow", "File Information", None, QtGui.QApplication.UnicodeUTF8))
        self.rawExportButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Advanced Raw Export", None, QtGui.QApplication.UnicodeUTF8))
        self.splitFileButton.setText(QtGui.QApplication.translate("MondoMainWindow", "Rend File Asunder", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MondoMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MondoMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCheckForUpdates.setTitle(QtGui.QApplication.translate("MondoMainWindow", "Check for Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MondoMainWindow", "About Mondo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MondoMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutLibraries.setText(QtGui.QApplication.translate("MondoMainWindow", "About Libraries", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateLatestStable.setText(QtGui.QApplication.translate("MondoMainWindow", "Latest Stable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSpecificBranch.setText(QtGui.QApplication.translate("MondoMainWindow", "Specific Branch...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSpecificCommit.setText(QtGui.QApplication.translate("MondoMainWindow", "Specific Commit..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateCurrentBranch.setText(QtGui.QApplication.translate("MondoMainWindow", "Latest branch", None, QtGui.QApplication.UnicodeUTF8))

