# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'psd_options.ui'
#
# Created: Wed Dec 14 16:37:41 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PSDOptionsWidget(object):
    def setupUi(self, PSDOptionsWidget):
        PSDOptionsWidget.setObjectName("PSDOptionsWidget")
        PSDOptionsWidget.resize(208, 191)
        self.formLayout = QtGui.QFormLayout(PSDOptionsWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.fftPointsLabel = QtGui.QLabel(PSDOptionsWidget)
        self.fftPointsLabel.setObjectName("fftPointsLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.fftPointsLabel)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.fftPoints = QtGui.QComboBox(PSDOptionsWidget)
        self.fftPoints.setObjectName("fftPoints")
        self.horizontalLayout_4.addWidget(self.fftPoints)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.durationLabel = QtGui.QLabel(PSDOptionsWidget)
        self.durationLabel.setObjectName("durationLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.durationLabel)
        self.duration = QtGui.QLabel(PSDOptionsWidget)
        self.duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.duration.setObjectName("duration")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.duration)
        self.resolutionLabel = QtGui.QLabel(PSDOptionsWidget)
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.resolutionLabel)
        self.resolution = QtGui.QLabel(PSDOptionsWidget)
        self.resolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolution.setObjectName("resolution")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.resolution)
        self.overlapPercentLabel = QtGui.QLabel(PSDOptionsWidget)
        self.overlapPercentLabel.setObjectName("overlapPercentLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.overlapPercentLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.overlapPercent = QtGui.QDoubleSpinBox(PSDOptionsWidget)
        self.overlapPercent.setMinimumSize(QtCore.QSize(75, 0))
        self.overlapPercent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overlapPercent.setDecimals(0)
        self.overlapPercent.setMaximum(95.0)
        self.overlapPercent.setSingleStep(5.0)
        self.overlapPercent.setProperty("value", 75.0)
        self.overlapPercent.setObjectName("overlapPercent")
        self.horizontalLayout_3.addWidget(self.overlapPercent)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.overlapPointsLabel = QtGui.QLabel(PSDOptionsWidget)
        self.overlapPointsLabel.setObjectName("overlapPointsLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.overlapPointsLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.overlapPoints = QtGui.QSpinBox(PSDOptionsWidget)
        self.overlapPoints.setMinimumSize(QtCore.QSize(75, 0))
        self.overlapPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overlapPoints.setObjectName("overlapPoints")
        self.horizontalLayout_5.addWidget(self.overlapPoints)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.windowCountLabel = QtGui.QLabel(PSDOptionsWidget)
        self.windowCountLabel.setObjectName("windowCountLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.windowCountLabel)
        self.windowCount = QtGui.QLabel(PSDOptionsWidget)
        self.windowCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.windowCount.setObjectName("windowCount")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.windowCount)
        self.windowFunctionLabel = QtGui.QLabel(PSDOptionsWidget)
        self.windowFunctionLabel.setObjectName("windowFunctionLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.windowFunctionLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.windowFunction = QtGui.QComboBox(PSDOptionsWidget)
        self.windowFunction.setObjectName("windowFunction")
        self.horizontalLayout_2.addWidget(self.windowFunction)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.detrendMethodLabel = QtGui.QLabel(PSDOptionsWidget)
        self.detrendMethodLabel.setObjectName("detrendMethodLabel")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.detrendMethodLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.detrendMethod = QtGui.QComboBox(PSDOptionsWidget)
        self.detrendMethod.setObjectName("detrendMethod")
        self.horizontalLayout.addWidget(self.detrendMethod)
        self.formLayout.setLayout(7, QtGui.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(PSDOptionsWidget)
        QtCore.QMetaObject.connectSlotsByName(PSDOptionsWidget)

    def retranslateUi(self, PSDOptionsWidget):
        PSDOptionsWidget.setWindowTitle(QtGui.QApplication.translate("PSDOptionsWidget", "PSD Options", None, QtGui.QApplication.UnicodeUTF8))
        self.fftPointsLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "FFT Window Size", None, QtGui.QApplication.UnicodeUTF8))
        self.durationLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "Window Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setText(QtGui.QApplication.translate("PSDOptionsWidget", "600 s", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "Frequency Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution.setText(QtGui.QApplication.translate("PSDOptionsWidget", "0.1 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.overlapPercentLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "Window Overlap Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.overlapPercent.setSuffix(QtGui.QApplication.translate("PSDOptionsWidget", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.overlapPointsLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "Window Overlap Points", None, QtGui.QApplication.UnicodeUTF8))
        self.windowCountLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "Number of Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.windowCount.setText(QtGui.QApplication.translate("PSDOptionsWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.windowFunctionLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "Window Function", None, QtGui.QApplication.UnicodeUTF8))
        self.detrendMethodLabel.setText(QtGui.QApplication.translate("PSDOptionsWidget", "Detrend Method", None, QtGui.QApplication.UnicodeUTF8))

