[tool.poetry]
name = "tablearn"
version = "0.1.0"
description = "tablearn: Learner for Tabular Data"
authors = ["yajiez <yajiez.me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.3"
torchvision = "^0.4.2"
pandas = "^0.25.3"
seaborn = "^0.9.0"
pendulum = "^2.0"
numpy = "^1.17"
xgboost = "^0.90.0"
scikit-learn = "^0.21.3"
catboost = "^0.20.0"
lightgbm = "^2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
ipython = "^7.10"
tox = "^3.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
