[tool.poetry]
name = "nuggan"
version = "0.2.0"
description = "A library for creating self-aware ids"
authors = ["Kevin Schiroo <kjschiroo@gmail.com>"]
license = "MIT"
repository = "https://github.com/kjschiroo/nuggan"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
watchdog = "^0.9.0"
pytest-cov = "^2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
