dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: MY5EqGSyszPWYXv6fw9eZmNBu6cIfi2TVwlBDFNvrRSZS1vJJBiJXv/0sLUpJCryR3Hq5ZdE1D4ZhnSEyQs8YYvJHLDiCD2IiGv2PAwI2HZp5wN5TSg/b5cE/OKaCbUnQ7rP2/rMExcE287uhvSupVminZBJt6ar9G0J+B4UB2LoTCgCQW54ZoMDmLS8N4L9kUtqCPqIapF5qS2XqZI3MRxkHjJSy5VHgcqwB8IhYppT3ETBZbLM4u5peRC99VhSW1Kt84OWWXiRc8U/mmb6Ci4AfYUzkhFubnZCSmXR1WYzgDNd+K+mDgnH/kiRw1SMO8czWQhwmb094LSJPXFsiJhSinXdyUucmtWx/OeNrDspx4sG4nUFjrlBjds56Ei7jhFjIeEpnsuwcRMeBnCvX12NUo7E36lzaI7+mCl/pyt/3NqEOurbkQ2BMdjIdlyHidjVHWlC10+pdqiOJp+WBuC6eHVw/5wyK0723a+5WEJMemh+TqvxX75VQJhs5yJzKbkvvxs447ILODLIW2e4CedTTz0KY6W0uNEaVjlfOtEKcN1EJSZnFdFZ6vUXB4YiXipvMA4OWMHVn8UAJmWNas1uIT3UZtGNZHsT5cYxUuL7EJmcOaMkMgb6S+jOxDAht+IoVwsvB0qdNbq+O5nMt0Tkm31270bRBwPVTUnabgw=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint simpleio.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-simpleio --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
