[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.scripts]
chrisbrake = "chrisbrake:main"


[tool.flit.metadata]
module = "chrisbrake"
author = "Chris Brake"
home-page = "https://github.com/chrisbrake/chrisbrake"
author-email = "chris.brake@gmail.com"
description-file = 'README.rst'
classifiers=[
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
requires=[
    "pynput"
]

[tool.flit.metadata.requires-extra]
test = [ "flake8", "pytest", "pytest-cov"]
doc = ["sphinx"]