dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: DHzhwDVhmIZEmfIPlOBgg+jif1lbKp8btvnzXtxaZIftLHBayY68IGOPD2SIEm/bIope3I4tknlsKgGdUbuSvDIgaPo7oeVP9LnqiWJzd86vh16UcydLEwIDN9AlSkzhz+d2Vz+DqYeSAo1nAsPXqKiuXQ7FzEqiAorOfcjBIZnZpi70OzmsjgZV5V8J9/xO0PkQH2K9AUjZ3zFNpcpvxOWhpjh8Rl75xxSTbf7YrABcZonHK20UnbCJblmYx36pUtYedUx5hsxymjEQQOhQ3OdQOWn2Xf2nROHDCx0lmoHJvHjhRWGRra7esAMbRMFvAvGzMMBThIOGTApo85oI4h3HhQBoxoi9NHzQUsn5/GDUlIZ17pRT+NJi+plea7Zmvd8gnLHSwDAu5BvyfF4Kfn0TOSrE7fSA4cCvHwbo+kS19zxYT9GXuLfjR4gBXgpbl5emVcbOMqIbskKPOplhZZ1z59ehyEfzidADR45gPXtc1vQhG+xURR8HzRUV9RUczIFQIEtlBYIa4d4R+XMS2aMM9zyB5qxQARt0wGGbvNnlsOinTHdMXsJNCQYJiTeboQ7aL88lIn+z73vS5+Ln2r+cOc1mUgzXiTFvJ5YDtLAJ3Od6boWj20qqYZF5NO9RfuwlpU7UeWHGYscz3EGDfhZdSj860YnJHA4Kuq+vzEU=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_max7219/*.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-max7219 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
