
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-16T10:10:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "85f18e9d1b469a39dde4d2150741c55c7d8163c2",
 "version": "3.0.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
